compressionLevel: 0

enableGlobalCache: false

enableImmutableCache: false

enableScripts: true

httpTimeout: 30000

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

networkConcurrency: 2

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin

unsafeHttpWhitelist:
  - "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
