# apps/frontend-blog/.env.app
# Capacitor App构建专用环境变量

BUILD_TARGET=app
NEXT_PUBLIC_APP_MODE=hybrid
NEXT_PUBLIC_CAPACITOR=true
NEXT_PUBLIC_ANDROID_PACKAGE=com.tarsier.labs
NEXT_PUBLIC_IOS_BUNDLE=com.tarsier.labs
NEXT_PUBLIC_VERSION=1.0.0
NEXT_PUBLIC_BUILD_NUMBER=1

# App模式下禁用部分Web特性
NEXT_PUBLIC_DISABLE_SERVICE_WORKER=true
NEXT_PUBLIC_DISABLE_PWA=true

# App模式API配置
NEXT_PUBLIC_API_BASE_URL=https://api.joyminis.com
NEXT_PUBLIC_API_TIMEOUT=30000

# App模式缓存配置
NEXT_PUBLIC_CACHE_ENABLED=true
NEXT_PUBLIC_CACHE_MAX_AGE=86400

# App模式调试配置
NEXT_PUBLIC_ENABLE_DEBUG=false
NEXT_PUBLIC_ENABLE_CONSOLE_LOG=false