#!/usr/bin/env bash
# ============================================================
# VPS 一次性初始化脚本 (Ubuntu 22.04, 8GB RAM, 8 CPU)
# ============================================================
# 使用方法:
#   scp deploy/server-init.sh root@<VPS_IP>:/root/
#   ssh root@<VPS_IP> 'chmod +x /root/server-init.sh && /root/server-init.sh'
# ============================================================
set -euo pipefail

VPS_IP="${VPS_IP:-}"
if [ -z "$VPS_IP" ]; then
    read -rp "请输入 VPS IP 地址: " VPS_IP
fi
PROJECT_DIR="/opt/lucky"
SWAP_SIZE="2G"

echo "============================================"
echo "  Lucky Nest VPS 初始化"
echo "  IP: $VPS_IP | RAM: 8GB | CPU: 8 Core"
echo "============================================"

# ------------------------------------------
# 1. 系统更新
# ------------------------------------------
echo "→ [1/8] 系统更新..."
apt-get update -y && apt-get upgrade -y
apt-get install -y curl wget git htop nano unzip fail2ban

# ------------------------------------------
# 2. 创建 Swap (2GB — 运行时安全网)
# ------------------------------------------
echo "→ [2/8] 配置 Swap ($SWAP_SIZE)..."
if [ ! -f /swapfile ]; then
    fallocate -l "$SWAP_SIZE" /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' >> /etc/fstab
    echo "    Swap 创建完成"
else
    echo "    Swap 已存在, 跳过"
fi

# 内核参数优化 (8核高并发服务器)
cat > /etc/sysctl.d/99-lucky.conf << 'EOF'
# Swap 使用倾向 (10 = 尽量少用, 保持内存优先)
vm.swappiness=10
# Redis AOF 需要
vm.overcommit_memory=1
# 网络优化 — 8核高并发
net.core.somaxconn=1024
net.ipv4.tcp_max_syn_backlog=1024
# 更快回收 TIME_WAIT 连接
net.ipv4.tcp_fin_timeout=30
# 提高文件描述符上限 (高并发需要)
fs.file-max=131072
EOF
sysctl --system

# ------------------------------------------
# 3. 安装 Docker Engine + Compose Plugin
# ------------------------------------------
echo "→ [3/8] 安装 Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo "    Docker 安装完成: $(docker --version)"
else
    echo "    Docker 已安装: $(docker --version)"
fi

# 验证 docker compose
docker compose version

# Docker daemon 优化 (日志限制)
mkdir -p /etc/docker
cat > /etc/docker/daemon.json << 'EOF'
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "50m",
    "max-file": "5"
  },
  "storage-driver": "overlay2"
}
EOF
systemctl restart docker

# ------------------------------------------
# 4. 防火墙 (UFW)
# ------------------------------------------
echo "→ [4/8] 配置防火墙..."
apt-get install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    # SSH
ufw allow 80/tcp    # HTTP
ufw allow 443/tcp   # HTTPS
ufw --force enable
ufw status verbose

# ------------------------------------------
# 5. Fail2Ban (SSH 防暴力)
# ------------------------------------------
echo "→ [5/8] 配置 Fail2Ban..."
cat > /etc/fail2ban/jail.local << 'EOF'
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 5
bantime = 3600
findtime = 600
EOF
systemctl enable fail2ban
systemctl restart fail2ban

# ------------------------------------------
# 6. 创建项目目录
# ------------------------------------------
echo "→ [6/8] 创建项目目录..."
mkdir -p "$PROJECT_DIR"/{certs,nginx/html,redis,deploy,data}

# ------------------------------------------
# 7. 安装 Certbot (Let's Encrypt)
# ------------------------------------------
echo "→ [7/8] 安装 Certbot..."
apt-get install -y certbot

# ------------------------------------------
# 8. 安装 coturn (TURN Server for WebRTC)
# ------------------------------------------
echo "→ [8/8] 安装 coturn TURN Server..."
TURN_SECRET="${TURN_SECRET:-}"
TURN_DOMAIN="${TURN_DOMAIN:-turn.joyminis.com}"
TURN_PORT="${TURN_PORT:-3478}"
TURN_MIN_PORT="${TURN_MIN_PORT:-49160}"
TURN_MAX_PORT="${TURN_MAX_PORT:-49200}"
TURN_CONF="/etc/turnserver.conf"
TURN_DEFAULTS="/etc/default/coturn"

if [ -z "$TURN_SECRET" ]; then
    echo "    ⚠️  TURN_SECRET 未设置，跳过 coturn 安装。"
    echo "    如需安装，请设置环境变量后重新运行:"
    echo "    export TURN_SECRET='your-long-random-secret'"
    echo "    bash /opt/lucky/deploy/install-turn.sh"
else
    apt-get install -y coturn

    # 启用 coturn 服务
    if grep -q '^#TURNSERVER_ENABLED=1' "$TURN_DEFAULTS" 2>/dev/null; then
        sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' "$TURN_DEFAULTS"
    elif grep -q '^TURNSERVER_ENABLED=' "$TURN_DEFAULTS" 2>/dev/null; then
        sed -i 's/^TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' "$TURN_DEFAULTS"
    else
        echo 'TURNSERVER_ENABLED=1' >> "$TURN_DEFAULTS"
    fi

    [ -f "$TURN_CONF" ] && cp "$TURN_CONF" "${TURN_CONF}.bak.$(date +%Y%m%d_%H%M%S)"

    cat > "$TURN_CONF" <<EOF
# Lucky Nest coturn configuration
# Generated by deploy/server-init.sh

listening-port=${TURN_PORT}
listening-ip=${VPS_IP}
external-ip=${VPS_IP}

min-port=${TURN_MIN_PORT}
max-port=${TURN_MAX_PORT}

use-auth-secret
static-auth-secret=${TURN_SECRET}
realm=${TURN_DOMAIN}
lt-cred-mech

fingerprint
no-cli
no-multicast-peers
no-tls
no-dtls

simple-log
log-file=/var/log/turnserver.log
EOF

    # 开放防火墙端口
    ufw allow ${TURN_PORT}/tcp || true
    ufw allow ${TURN_PORT}/udp || true
    ufw allow ${TURN_MIN_PORT}:${TURN_MAX_PORT}/udp || true
    ufw reload || true

    systemctl enable coturn
    systemctl restart coturn
    echo "    coturn 安装完成: $(turnserver --version 2>&1 | head -1 || echo 'ok')"
fi

echo ""
echo "============================================"
echo "   初始化完成！"
echo "============================================"
echo ""
echo "后续步骤:"
echo ""
echo "  1. 确认 DNS A 记录指向 $VPS_IP (Cloudflare 代理均已关闭灰云):"
echo "     - api.joyminis.com    → $VPS_IP"
echo "     - turn.joyminis.com   → $VPS_IP (灰云, 不走 CF 代理)"
echo ""
echo "  2. 申请 SSL 证书:"
echo "     certbot certonly --standalone \\"
echo "       -d api.joyminis.com \\"
echo "       --agree-tos -m your@email.com"
echo ""
echo "  3. 复制证书到项目目录:"
echo "     cp /etc/letsencrypt/live/api.joyminis.com/fullchain.pem $PROJECT_DIR/certs/server.crt"
echo "     cp /etc/letsencrypt/live/api.joyminis.com/privkey.pem   $PROJECT_DIR/certs/server.key"
echo ""
echo "  4. 上传 .env.prod 并部署:"
echo "     scp deploy/.env.prod root@$VPS_IP:$PROJECT_DIR/deploy/"
echo "     ./deploy/deploy.sh"
echo ""
echo "  5. 安装证书自动续期 cron (每周一凌晨 3 点):"
echo "     scp deploy/renew-cert.sh root@$VPS_IP:$PROJECT_DIR/deploy/"
echo "     ssh root@$VPS_IP 'chmod +x $PROJECT_DIR/deploy/renew-cert.sh'"
echo "     ssh root@$VPS_IP '(crontab -l 2>/dev/null; echo \"0 3 * * 1 $PROJECT_DIR/deploy/renew-cert.sh >> /var/log/lucky-cert.log 2>&1\") | crontab -'"
echo ""
echo "  6. 安装监控 cron (每 5 分钟):"
echo "     ssh root@$VPS_IP '(crontab -l 2>/dev/null; echo \"*/5 * * * * $PROJECT_DIR/deploy/monitor.sh >> /var/log/lucky-monitor.log 2>&1\") | crontab -'"
echo ""
echo "  7. 安装备份 cron (每天凌晨 3 点):"
echo "     ssh root@$VPS_IP '(crontab -l 2>/dev/null; echo \"0 3 * * * $PROJECT_DIR/deploy/backup.sh >> /var/log/lucky-backup.log 2>&1\") | crontab -'"
echo ""

