import type { Locale } from '@lucky/shared';

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    users: 'User Management',
    admin: 'Admin Accounts',
    products: 'Products',
    categories: 'Categories',
    actSection: 'Act Sections',
    banners: 'Banners',
    groups: 'Group Buying',
    orders: 'Orders & Delivery',
    kyc: 'KYC Review',
    address: 'Address',
    marketing: 'Marketing',
    finance: 'Finance Center',
    finance_page: 'Finance',
    paymentChannels: 'Payment Channels',
    logout: 'Logout',
    revenue: 'Total Revenue',
    activeUsers: 'Active Users',
    newOrders: 'New Orders',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    status: 'Status',
    actions: 'Actions',
    kyc_pending: 'KYC Pending',
    notifications: 'Notifications',
    analytics: 'Data Analytics',
    operationLogs: 'Operation Logs',
    roles: 'Role Management',
    im: 'Customer Service',
    supportChannels: 'Support Channels',
    ads: 'Advertisements',
    flashSale: 'Flash Sale',
    loginLogs: 'Login Logs',
    luckyDraw: 'Lucky Draw',
    settings: 'System Config',
    pendingApplications: 'Pending Applications',

    // Blog Translation Progress Page
    blog_translation_pageTitle: 'Translation Progress Monitor',
    blog_translation_pageSubtitle:
      'Real-time monitoring of blog content translation progress and status',
    blog_translation_autoRefreshOn: 'Auto refreshing',
    blog_translation_autoRefreshOff: 'Enable auto refresh',
    blog_translation_manualRefresh: 'Manual refresh',
    blog_translation_overallProgress: 'Overall Progress',
    blog_translation_completed: 'Completed',
    blog_translation_inProgress: 'In Progress',
    blog_translation_failed: 'Failed',
    blog_translation_completedItems: '{completed} / {total} items completed',
    blog_translation_articleTranslation: 'Article Translation',
    blog_translation_categoryTranslation: 'Category Translation',
    blog_translation_tagTranslation: 'Tag Translation',
    blog_translation_queueStatus: 'Queue Status',
    blog_translation_timeInfo: 'Time Information',
    blog_translation_startTime: 'Start Time',
    blog_translation_notStarted: 'Not started',
    blog_translation_elapsedTime: 'Elapsed',
    blog_translation_estimatedCompletion: 'Estimated completion',
    blog_translation_unknown: 'Unknown',
    blog_translation_pendingArticlesTitle: '🔍 Pending Articles ({lang})',
    blog_translation_pendingArticlesDescription:
      '{count} articles pending {lang} translation',
    blog_translation_allArticlesTranslated: 'All articles translated',
    blog_translation_allArticlesTranslatedDesc:
      'All articles for language ({lang}) have translations',
    blog_translation_statusCompleted: 'Completed',
    blog_translation_statusProcessing: 'Processing {progress}%',
    blog_translation_statusQueued: 'Queued',
    blog_translation_statusFailed: 'Failed',
    blog_translation_statusUntranslated: 'Untranslated',
    blog_translation_translateButton: 'Translate',
    blog_translation_activeJobsTitle: '⚡ Active Translation Jobs ({count})',
    blog_translation_noActiveJobs: 'No active translation jobs',
    blog_translation_typeArticle: 'Article',
    blog_translation_typeCategory: 'Category',
    blog_translation_typeTag: 'Tag',
    blog_translation_issuesDetectionTitle: '🔍 Translation Issues Detection',
    blog_translation_targetLanguage: 'Target Language',
    blog_translation_recheck: 'Recheck',
    blog_translation_selectAll: 'Select All',
    blog_translation_deselectAll: 'Deselect All',
    blog_translation_fixAll: 'Fix All Issues',
    blog_translation_fixSelected: 'Fix Selected ({count})',
    blog_translation_issuesFound:
      '{count} articles with translation issues found',
    blog_translation_articleTitle: 'Article Title',
    blog_translation_issueType: 'Issue Type',
    blog_translation_severity: 'Severity',
    blog_translation_issueTitleNotTranslated: 'Title not translated',
    blog_translation_issueContentIncomplete: 'Content incomplete',
    blog_translation_issueNotTranslated: 'Not translated',
    blog_translation_issueFailed: 'Translation failed',
    blog_translation_severityHigh: 'High',
    blog_translation_severityMedium: 'Medium',
    blog_translation_severityLow: 'Low',
    blog_translation_fixSingle: 'Fix',
    blog_translation_noIssuesFound: 'No translation issues found',
    blog_translation_noIssuesFoundDesc:
      'All articles for language ({lang}) are properly translated',
    blog_translation_jobHistoryTitle: '📋 Translation Job History',
    blog_translation_filter: 'Filter',
    blog_translation_showOnlyActive:
      'Show only active jobs (QUEUED/PROCESSING)',
    blog_translation_perPage: 'Per page',
    blog_translation_perPageItems: '{count} items',
    blog_translation_prevPage: 'Previous',
    blog_translation_currentPage: 'Page {page}',
    blog_translation_nextPage: 'Next',
    blog_translation_name: 'Name',
    blog_translation_type: 'Type',
    blog_translation_targetLang: 'Target',
    blog_translation_status: 'Status',
    blog_translation_progress: 'Progress',
    blog_translation_createdAt: 'Created At',
    blog_translation_errorMsg: 'Error',
    blog_translation_totalRecords:
      '{total} records total, page {page} / {totalPages}',
    blog_translation_noJobRecords: 'No job records',
    blog_translation_liveJobsTitle: 'Live Job Queue',
    blog_translation_activeJobs: 'Active Jobs ({count})',
    blog_translation_waitingJobs: 'Waiting Jobs ({count})',
    blog_translation_failedJobs: 'Failed Jobs ({count})',
    blog_translation_moreWaitingJobs: '{count} more jobs waiting',
    blog_translation_retry: 'Retry',
    blog_translation_moreFailedJobs: '{count} more failed jobs',
    blog_translation_noLiveJobs: 'No active jobs in queue',
    blog_translation_failedJobsAlertTitle: 'Failed jobs detected',
    blog_translation_failedJobsAlertDesc:
      '{count} translation jobs failed, check failed jobs list.',
    blog_translation_notStartedAlertTitle: 'Translation not started',
    blog_translation_notStartedAlertDesc:
      'All translation jobs are waiting, check queue status.',
    blog_translation_completedAlertTitle: 'Translation completed',
    blog_translation_completedAlertDesc:
      'All translation jobs finished successfully!',
    blog_translation_loadFailedTitle: 'Load failed',
    blog_translation_loadFailedDesc: 'Failed to load translation progress data',
    blog_translation_retryButton: 'Retry',
    blog_translation_batchFixStarted: 'Batch fix started, {count} jobs queued',
    blog_translation_batchFixFailed: 'Batch fix failed, please try again later',
    blog_translation_batchFixNetworkError:
      'Batch fix failed, check network connection',
    blog_translation_seconds: '0s',
    blog_translation_progressWithPercent: 'Progress: {progress}%',
    blog_translation_waiting: 'Waiting...',
    blog_translation_unknownError: 'Unknown error',
    blog_article_translationRequestSent:
      'Translation request sent, will refresh automatically',
    blog_article_translationFailed:
      'Translation failed, please try again later',
    blog_article_retranslate: 'Retranslate',
    blog_article_autoTranslateAfterSave:
      'Auto-translate English version after saving',

    // Blog Dashboard Page
    blog_dashboard_pageTitle: 'Blog Management',
    blog_dashboard_pageDescription:
      'Manage blog articles, categories, tags, and comments',
    blog_dashboard_writeNewArticle: 'Write New Article',
    blog_dashboard_totalArticles: 'Total Articles',
    blog_dashboard_categories: 'Categories',
    blog_dashboard_tags: 'Tags',
    blog_dashboard_pendingComments: 'Pending Comments',
    blog_dashboard_recentArticles: 'Recent Articles',
    blog_dashboard_viewAll: 'View All',
    blog_dashboard_article: 'Article',
    blog_dashboard_status: 'Status',
    blog_dashboard_views: 'Views',
    blog_dashboard_comments: 'Comments',
    blog_dashboard_published: 'Published',
    blog_dashboard_notPublished: 'Not published',
    blog_dashboard_topPerformingArticles: 'Top Performing Articles',
    blog_dashboard_recentActivity: 'Recent Activity',
    blog_dashboard_blogSystemReady: 'Blog system is ready',
    blog_dashboard_backendApiReady:
      'Backend API fully implemented, ready to create content',
    blog_dashboard_welcomeToBlogSystem: 'Welcome to the blog system',
    blog_dashboard_startCreatingFirstArticle:
      'Start creating your first blog article',
    blog_dashboard_analyticsDashboardAdded: 'Analytics dashboard added',
    blog_dashboard_trackArticlePerformance:
      'Track article performance and user engagement',
    blog_dashboard_justNow: 'Just now',
    blog_dashboard_hoursAgo: '2 hours ago',
    blog_dashboard_loadingBlogDashboard: 'Loading blog dashboard...',
    blog_dashboard_numberOfPublishedArticles: 'Number of published articles',
    blog_dashboard_numberOfArticleCategories: 'Number of article categories',
    blog_dashboard_numberOfArticleTags: 'Number of article tags',
    blog_dashboard_commentsAwaitingModeration: 'Comments awaiting moderation',

    // Blog Articles Page
    blog_articles_pageTitle: 'Article Management',
    blog_articles_pageDescription:
      'Manage blog articles including creation, editing, publishing, and deletion',
    blog_articles_newArticle: 'New Article',
    blog_articles_articleList: 'Article List',
    blog_articles_search: 'Search',
    blog_articles_searchPlaceholder: 'Search article titles or content...',
    blog_articles_status: 'Status',
    blog_articles_allStatus: 'All Status',
    blog_articles_published: 'Published',
    blog_articles_draft: 'Draft',
    blog_articles_archived: 'Archived',
    blog_articles_category: 'Category',
    blog_articles_allCategories: 'All Categories',
    blog_articles_article: 'Article',
    blog_articles_tags: 'Tags',
    blog_articles_metrics: 'Metrics',
    blog_articles_views: 'views',
    blog_articles_comments: 'comments',
    blog_articles_publishedDate: 'Published',
    blog_articles_notPublished: 'Not published',
    blog_articles_actions: 'Actions',
    blog_articles_preview: 'Preview',
    blog_articles_edit: 'Edit',
    blog_articles_unpublish: 'Unpublish',
    blog_articles_publish: 'Publish',
    blog_articles_delete: 'Delete',
    blog_articles_deleteArticle: 'Delete Article?',
    blog_articles_deleteConfirm: 'Delete',
    blog_articles_cancel: 'Cancel',
    blog_articles_articleDeleted: 'Article deleted successfully',
    blog_articles_deleteFailed: 'Failed to delete article',
    blog_articles_publishArticle: 'Publish Article?',
    blog_articles_publishConfirm: 'Publish',
    blog_articles_articlePublished: 'Article published successfully',
    blog_articles_publishFailed: 'Failed to publish article',
    blog_articles_unpublishArticle: 'Unpublish Article?',
    blog_articles_unpublishConfirm: 'Unpublish',
    blog_articles_articleUnpublished: 'Article unpublished successfully',
    blog_articles_unpublishFailed: 'Failed to unpublish article',
    blog_articles_actionCannotBeUndone: '⚠️ This action cannot be undone.',
    blog_articles_articleWillBePublic: '📢 Article will be publicly visible',
    blog_articles_articleWillBeHidden: '⚠️ Article will be hidden from public',
    blog_articles_articleDetails: 'Article Details:',
    blog_articles_slug: 'Slug:',
    blog_articles_author: 'Author:',
    blog_articles_uncategorized: 'Uncategorized',
    blog_articles_admin: 'Admin',
    blog_articles_min: 'min',

    // Blog Categories Page
    blog_categories_pageTitle: 'Category Management',
    blog_categories_pageDescription:
      'Manage blog categories for organizing articles',
    blog_categories_newCategory: 'New Category',
    blog_categories_categoryList: 'Category List',
    blog_categories_search: 'Search',
    blog_categories_searchPlaceholder: 'Search by name or description...',
    blog_categories_name: 'Name',
    blog_categories_slug: 'Slug',
    blog_categories_description: 'Description',
    blog_categories_articles: 'Articles',
    blog_categories_created: 'Created',
    blog_categories_actions: 'Actions',
    blog_categories_deleteCategory: 'Delete Category?',
    blog_categories_deleteConfirm: 'Delete',
    blog_categories_cancel: 'Cancel',
    blog_categories_categoryDeleted: 'Category deleted successfully',
    blog_categories_deleteFailed: 'Failed to delete category',
    blog_categories_actionCannotBeUndone: '⚠️ This action cannot be undone.',
    blog_categories_categoryDetails: 'Category Details:',
    blog_categories_noDescription: 'No description',
    blog_categories_uncategorized: 'Uncategorized',
    blog_categories_categoryUsageTips: 'Category Usage Tips',
    blog_categories_tip1:
      'Categories help organize articles into logical groups',
    blog_categories_tip2: 'Each article can belong to only one category',
    blog_categories_tip3:
      'URL slugs should be lowercase with hyphens (e.g., "web-development")',
    blog_categories_tip4:
      'Categories with articles cannot be deleted - move articles first',
    blog_categories_thisCategoryContains:
      'This category contains {count} articles.',
    blog_categories_articlesWillBeMoved:
      'These articles will be moved to "Uncategorized".',

    // Blog Tags Page
    blog_tags_pageTitle: 'Tag Management',
    blog_tags_pageDescription:
      'Manage blog tags for categorizing and organizing articles',
    blog_tags_newTag: 'New Tag',
    blog_tags_tagList: 'Tag List',
    blog_tags_search: 'Search',
    blog_tags_searchPlaceholder: 'Search tags by name or description...',
    blog_tags_totalTags: 'Total Tags',
    blog_tags_taggedArticles: 'Tagged Articles',
    blog_tags_totalTagsCount: 'Total {count} tags',
    blog_tags_name: 'Name',
    blog_tags_slug: 'Slug',
    blog_tags_description: 'Description',
    blog_tags_articles: 'articles',
    blog_tags_uses: 'uses',
    blog_tags_created: 'Created',
    blog_tags_actions: 'Actions',
    blog_tags_deleteTag: 'Delete Tag?',
    blog_tags_deleteConfirm: 'Delete',
    blog_tags_cancel: 'Cancel',
    blog_tags_tagDeleted: 'Tag deleted successfully',
    blog_tags_deleteFailed: 'Failed to delete tag',
    blog_tags_loadFailed: 'Failed to load tags',
    blog_tags_actionCannotBeUndone: 'This action cannot be undone.',
    blog_tags_loadingTags: 'Loading tags...',
    blog_tags_noDescription: 'No description',
    blog_tags_tagUsageTips: 'Tag Usage Tips',
    blog_tags_tip1: 'Tags help categorize articles with multiple topics',
    blog_tags_tip2: 'Each article can have multiple tags (unlike categories)',
    blog_tags_tip3: 'Use specific, descriptive tags rather than generic ones',
    blog_tags_tip4: 'Popular tags are automatically highlighted in the blog',
    blog_tags_tip5: 'Tags can be merged if you have similar ones',
    blog_tags_showingTags: 'Showing 1 to {current} of {total} tags',

    // Blog Comments Page
    blog_comments_pageTitle: 'Comment Management',
    blog_comments_pageDescription:
      'Moderate and manage user comments on blog articles',
    blog_comments_loadingComments: 'Loading comments...',
    blog_comments_totalComments: 'Total Comments',
    blog_comments_approved: 'Approved',
    blog_comments_pending: 'Pending',
    blog_comments_spam: 'Spam',
    blog_comments_searchPlaceholder: 'Search comments by content or author...',
    blog_comments_allStatus: 'All Status',
    blog_comments_allArticles: 'All Articles',
    blog_comments_commentList: 'Comment List',
    blog_comments_totalCommentsCount: 'Total {count} comments',
    blog_comments_pendingModeration: '{count} pending moderation',
    blog_comments_author: 'Author',
    blog_comments_email: 'Email',
    blog_comments_content: 'Content',
    blog_comments_article: 'Article',
    blog_comments_createdAt: 'Created',
    blog_comments_ipAddress: 'IP Address',
    blog_comments_actions: 'Actions',
    blog_comments_approve: 'Approve',
    blog_comments_reject: 'Reject',
    blog_comments_edit: 'Edit',
    blog_comments_delete: 'Delete',
    blog_comments_viewArticle: 'View Article',
    blog_comments_reply: 'Reply',
    blog_comments_commentApproved: 'Comment approved successfully',
    blog_comments_approveFailed: 'Failed to approve comment',
    blog_comments_commentRejected: 'Comment rejected successfully',
    blog_comments_rejectFailed: 'Failed to reject comment',
    blog_comments_commentDeleted: 'Comment deleted successfully',
    blog_comments_deleteFailed: 'Failed to delete comment',
    blog_comments_loadFailed: 'Failed to load comments',
    blog_comments_deleteConfirm:
      'Are you sure you want to delete this comment? This action cannot be undone.',
    blog_comments_moderationTips: 'Comment Moderation Tips',
    blog_comments_tip1:
      'Review pending comments regularly to maintain engagement',
    blog_comments_tip2:
      'Mark obvious spam comments to help improve automatic filtering',
    blog_comments_tip3:
      'Consider replying to constructive comments to build community',
    blog_comments_tip4:
      'Check IP addresses and user agents for suspicious patterns',
    blog_comments_tip5:
      'Use the search feature to find comments by specific users',
    blog_comments_showingComments: 'Showing 1 to {current} of {total} comments',
    blog_comments_unknownArticle: 'Unknown Article',
    blog_comments_untitled: 'Untitled',
  },
  zh: {
    dashboard: '仪表盘',
    users: '用户管理',
    admin: '管理员账号',
    products: '商品管理',
    categories: '分类管理',
    actSection: '活动区块',
    banners: 'Banner广告',
    groups: '拼团管理',
    orders: '订单与发货',
    kyc: 'KYC审核',
    address: '地址管理',
    marketing: '营销中心',
    finance: '财务中心',
    finance_page: '财务',
    paymentChannels: '支付渠道',
    logout: '退出登录',
    revenue: '总收入',
    activeUsers: '活跃用户',
    newOrders: '新增订单',
    add: '新增',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    search: '搜索...',
    status: '状态',
    actions: '操作',
    kyc_pending: 'KYC待审核',
    notifications: '通知管理',
    analytics: '数据分析',
    operationLogs: '操作日志',
    roles: '角色管理',
    im: '客服中心',
    supportChannels: '客服渠道',
    ads: '广告管理',
    flashSale: '限时秒杀',
    loginLogs: '登录日志',
    luckyDraw: '幸运抽奖',
    settings: '系统配置',
    pendingApplications: '待审核申请',

    // Blog Translation Progress Page
    blog_translation_pageTitle: '翻译进度监控',
    blog_translation_pageSubtitle: '实时监控博客内容翻译进度和状态',
    blog_translation_autoRefreshOn: '自动刷新中',
    blog_translation_autoRefreshOff: '开启自动刷新',
    blog_translation_manualRefresh: '手动刷新',
    blog_translation_overallProgress: '总体进度',
    blog_translation_completed: '完成',
    blog_translation_inProgress: '进行中',
    blog_translation_failed: '失败',
    blog_translation_completedItems: '已完成 {completed} / {total} 个项目',
    blog_translation_articleTranslation: '文章翻译',
    blog_translation_categoryTranslation: '分类翻译',
    blog_translation_tagTranslation: '标签翻译',
    blog_translation_queueStatus: '队列状态',
    blog_translation_timeInfo: '时间信息',
    blog_translation_startTime: '开始时间',
    blog_translation_notStarted: '未开始',
    blog_translation_elapsedTime: '已运行',
    blog_translation_estimatedCompletion: '预计完成',
    blog_translation_unknown: '未知',
    blog_translation_pendingArticlesTitle: '🔍 待翻译文章 ({lang})',
    blog_translation_pendingArticlesDescription:
      '共 {count} 篇文章尚未完成 {lang} 语言翻译',
    blog_translation_allArticlesTranslated: '所有文章已完成翻译',
    blog_translation_allArticlesTranslatedDesc:
      '当前语言 ({lang}) 的所有文章都有翻译版本',
    blog_translation_statusCompleted: '已完成',
    blog_translation_statusProcessing: '处理中 {progress}%',
    blog_translation_statusQueued: '排队中',
    blog_translation_statusFailed: '失败',
    blog_translation_statusUntranslated: '未翻译',
    blog_translation_translateButton: '翻译',
    blog_translation_activeJobsTitle: '⚡ 活跃翻译任务 ({count} 个)',
    blog_translation_noActiveJobs: '当前没有活跃翻译任务',
    blog_translation_typeArticle: '文章',
    blog_translation_typeCategory: '分类',
    blog_translation_typeTag: '标签',
    blog_translation_issuesDetectionTitle: '🔍 问题文章检测',
    blog_translation_targetLanguage: '目标语言',
    blog_translation_recheck: '重新检测',
    blog_translation_selectAll: '全选',
    blog_translation_deselectAll: '取消全选',
    blog_translation_fixAll: '修复所有问题',
    blog_translation_fixSelected: '修复选中 ({count})',
    blog_translation_issuesFound: '发现 {count} 篇文章有翻译问题',
    blog_translation_articleTitle: '文章标题',
    blog_translation_issueType: '问题类型',
    blog_translation_severity: '严重程度',
    blog_translation_issueTitleNotTranslated: '标题未翻译',
    blog_translation_issueContentIncomplete: '内容不完整',
    blog_translation_issueNotTranslated: '未翻译',
    blog_translation_issueFailed: '翻译失败',
    blog_translation_severityHigh: '高',
    blog_translation_severityMedium: '中',
    blog_translation_severityLow: '低',
    blog_translation_fixSingle: '单独修复',
    blog_translation_noIssuesFound: '未发现翻译问题',
    blog_translation_noIssuesFoundDesc: '当前语言 ({lang}) 的所有文章翻译正常',
    blog_translation_jobHistoryTitle: '📋 翻译任务记录（持久化）',
    blog_translation_filter: '筛选',
    blog_translation_showOnlyActive: '仅显示活跃任务 (QUEUED/PROCESSING)',
    blog_translation_perPage: '每页',
    blog_translation_perPageItems: '{count}条',
    blog_translation_prevPage: '上一页',
    blog_translation_currentPage: '第 {page} 页',
    blog_translation_nextPage: '下一页',
    blog_translation_name: '名称',
    blog_translation_type: '类型',
    blog_translation_targetLang: '目标语言',
    blog_translation_status: '状态',
    blog_translation_progress: '进度',
    blog_translation_createdAt: '创建时间',
    blog_translation_errorMsg: '错误信息',
    blog_translation_totalRecords:
      '共 {total} 条记录，第 {page} / {totalPages} 页',
    blog_translation_noJobRecords: '暂无翻译任务记录',
    blog_translation_liveJobsTitle: '实时任务列表',
    blog_translation_activeJobs: '进行中的任务 ({count})',
    blog_translation_waitingJobs: '等待中的任务 ({count})',
    blog_translation_failedJobs: '失败的任务 ({count})',
    blog_translation_moreWaitingJobs: '还有 {count} 个任务在等待中',
    blog_translation_retry: '重试',
    blog_translation_moreFailedJobs: '还有 {count} 个失败任务',
    blog_translation_noLiveJobs: '当前没有活跃的翻译任务',
    blog_translation_failedJobsAlertTitle: '存在失败任务',
    blog_translation_failedJobsAlertDesc:
      '有 {count} 个翻译任务失败，请检查失败任务列表。',
    blog_translation_notStartedAlertTitle: '翻译未开始',
    blog_translation_notStartedAlertDesc:
      '所有翻译任务都在等待中，请检查队列状态。',
    blog_translation_completedAlertTitle: '翻译完成',
    blog_translation_completedAlertDesc: '所有翻译任务已完成！',
    blog_translation_loadFailedTitle: '加载失败',
    blog_translation_loadFailedDesc: '无法获取翻译进度数据',
    blog_translation_retryButton: '重试',
    blog_translation_batchFixStarted:
      '批量修复已启动，已投递 {count} 个修复任务到队列',
    blog_translation_batchFixFailed: '批量修复失败，请稍后重试',
    blog_translation_batchFixNetworkError: '批量修复失败，请检查网络连接',
    blog_translation_seconds: '0秒',
    blog_translation_progressWithPercent: '进度: {progress}%',
    blog_translation_waiting: '等待中...',
    blog_translation_unknownError: '未知错误',
    blog_article_translationRequestSent: '翻译请求已发送，稍后将自动刷新',
    blog_article_translationFailed: '翻译失败，请稍后重试',
    blog_article_retranslate: '重新翻译',
    blog_article_autoTranslateAfterSave: '保存后自动翻译英文版本',

    // Blog Dashboard Page
    blog_dashboard_pageTitle: '博客管理',
    blog_dashboard_pageDescription: '管理博客文章、分类、标签和评论',
    blog_dashboard_writeNewArticle: '写新文章',
    blog_dashboard_totalArticles: '文章总数',
    blog_dashboard_categories: '分类',
    blog_dashboard_tags: '标签',
    blog_dashboard_pendingComments: '待审核评论',
    blog_dashboard_recentArticles: '最近文章',
    blog_dashboard_viewAll: '查看全部',
    blog_dashboard_article: '文章',
    blog_dashboard_status: '状态',
    blog_dashboard_views: '浏览量',
    blog_dashboard_comments: '评论',
    blog_dashboard_published: '发布时间',
    blog_dashboard_notPublished: '未发布',
    blog_dashboard_topPerformingArticles: '热门文章',
    blog_dashboard_recentActivity: '最近动态',
    blog_dashboard_blogSystemReady: '博客系统已就绪',
    blog_dashboard_backendApiReady: '后端API已完全实现，可以开始创建内容',
    blog_dashboard_welcomeToBlogSystem: '欢迎使用博客系统',
    blog_dashboard_startCreatingFirstArticle: '开始创建您的第一篇博客文章',
    blog_dashboard_analyticsDashboardAdded: '分析仪表板已添加',
    blog_dashboard_trackArticlePerformance: '跟踪文章表现和用户参与度',
    blog_dashboard_justNow: '刚刚',
    blog_dashboard_hoursAgo: '2小时前',
    blog_dashboard_loadingBlogDashboard: '正在加载博客仪表板...',
    blog_dashboard_numberOfPublishedArticles: '已发布文章数量',
    blog_dashboard_numberOfArticleCategories: '文章分类数量',
    blog_dashboard_numberOfArticleTags: '文章标签数量',
    blog_dashboard_commentsAwaitingModeration: '等待审核的评论',

    // Blog Articles Page
    blog_articles_pageTitle: '文章管理',
    blog_articles_pageDescription: '管理博客文章，包括创建、编辑、发布和删除',
    blog_articles_newArticle: '新建文章',
    blog_articles_articleList: '文章列表',
    blog_articles_search: '搜索',
    blog_articles_searchPlaceholder: '搜索文章标题或内容...',
    blog_articles_status: '状态',
    blog_articles_allStatus: '所有状态',
    blog_articles_published: '已发布',
    blog_articles_draft: '草稿',
    blog_articles_archived: '已归档',
    blog_articles_category: '分类',
    blog_articles_allCategories: '所有分类',
    blog_articles_article: '文章',
    blog_articles_tags: '标签',
    blog_articles_metrics: '数据',
    blog_articles_views: '浏览量',
    blog_articles_comments: '评论',
    blog_articles_publishedDate: '发布时间',
    blog_articles_notPublished: '未发布',
    blog_articles_actions: '操作',
    blog_articles_preview: '预览',
    blog_articles_edit: '编辑',
    blog_articles_unpublish: '取消发布',
    blog_articles_publish: '发布',
    blog_articles_delete: '删除',
    blog_articles_deleteArticle: '删除文章？',
    blog_articles_deleteConfirm: '删除',
    blog_articles_cancel: '取消',
    blog_articles_articleDeleted: '文章删除成功',
    blog_articles_deleteFailed: '删除文章失败',
    blog_articles_publishArticle: '发布文章？',
    blog_articles_publishConfirm: '发布',
    blog_articles_articlePublished: '文章发布成功',
    blog_articles_publishFailed: '发布文章失败',
    blog_articles_unpublishArticle: '取消发布文章？',
    blog_articles_unpublishConfirm: '取消发布',
    blog_articles_articleUnpublished: '文章取消发布成功',
    blog_articles_unpublishFailed: '取消发布文章失败',
    blog_articles_actionCannotBeUndone: '⚠️ 此操作无法撤销。',
    blog_articles_articleWillBePublic: '📢 文章将对公众可见',
    blog_articles_articleWillBeHidden: '⚠️ 文章将对公众隐藏',
    blog_articles_articleDetails: '文章详情：',
    blog_articles_slug: '链接：',
    blog_articles_author: '作者：',
    blog_articles_uncategorized: '未分类',
    blog_articles_admin: '管理员',
    blog_articles_min: '分钟',

    // Blog Categories Page
    blog_categories_pageTitle: '分类管理',
    blog_categories_pageDescription: '管理博客分类，用于组织文章',
    blog_categories_newCategory: '新建分类',
    blog_categories_categoryList: '分类列表',
    blog_categories_search: '搜索',
    blog_categories_searchPlaceholder: '按名称或描述搜索...',
    blog_categories_name: '名称',
    blog_categories_slug: '链接',
    blog_categories_description: '描述',
    blog_categories_articles: '文章数',
    blog_categories_created: '创建时间',
    blog_categories_actions: '操作',
    blog_categories_deleteCategory: '删除分类？',
    blog_categories_deleteConfirm: '删除',
    blog_categories_cancel: '取消',
    blog_categories_categoryDeleted: '分类删除成功',
    blog_categories_deleteFailed: '删除分类失败',
    blog_categories_actionCannotBeUndone: '⚠️ 此操作无法撤销。',
    blog_categories_categoryDetails: '分类详情：',
    blog_categories_noDescription: '无描述',
    blog_categories_uncategorized: '未分类',
    blog_categories_categoryUsageTips: '分类使用提示',
    blog_categories_tip1: '分类帮助将文章组织成逻辑组',
    blog_categories_tip2: '每篇文章只能属于一个分类',
    blog_categories_tip3:
      'URL链接应为小写并用连字符连接（例如："web-development"）',
    blog_categories_tip4: '包含文章的分类无法删除 - 请先移动文章',
    blog_categories_thisCategoryContains: '此分类包含 {count} 篇文章。',
    blog_categories_articlesWillBeMoved: '这些文章将被移动到"未分类"。',

    // Blog Tags Page
    blog_tags_pageTitle: '标签管理',
    blog_tags_pageDescription: '管理博客标签，用于分类和组织文章',
    blog_tags_newTag: '新建标签',
    blog_tags_tagList: '标签列表',
    blog_tags_search: '搜索',
    blog_tags_searchPlaceholder: '按名称或描述搜索标签...',
    blog_tags_totalTags: '标签总数',
    blog_tags_taggedArticles: '已标记文章',
    blog_tags_totalTagsCount: '共 {count} 个标签',
    blog_tags_name: '名称',
    blog_tags_slug: '链接',
    blog_tags_description: '描述',
    blog_tags_articles: '篇文章',
    blog_tags_uses: '次使用',
    blog_tags_created: '创建时间',
    blog_tags_actions: '操作',
    blog_tags_deleteTag: '删除标签？',
    blog_tags_deleteConfirm: '删除',
    blog_tags_cancel: '取消',
    blog_tags_tagDeleted: '标签删除成功',
    blog_tags_deleteFailed: '删除标签失败',
    blog_tags_loadFailed: '加载标签失败',
    blog_tags_actionCannotBeUndone: '此操作无法撤销。',
    blog_tags_loadingTags: '正在加载标签...',
    blog_tags_noDescription: '无描述',
    blog_tags_tagUsageTips: '标签使用提示',
    blog_tags_tip1: '标签帮助将文章按多个主题分类',
    blog_tags_tip2: '每篇文章可以有多个标签（与分类不同）',
    blog_tags_tip3: '使用具体、描述性的标签，而不是通用标签',
    blog_tags_tip4: '热门标签会在博客中自动高亮显示',
    blog_tags_tip5: '如果有相似的标签，可以合并它们',
    blog_tags_showingTags: '显示第 1 到 {current} 个标签，共 {total} 个',

    // Blog Comments Page
    blog_comments_pageTitle: '评论管理',
    blog_comments_pageDescription: '审核和管理博客文章的用户评论',
    blog_comments_loadingComments: '正在加载评论...',
    blog_comments_totalComments: '评论总数',
    blog_comments_approved: '已批准',
    blog_comments_pending: '待审核',
    blog_comments_spam: '垃圾评论',
    blog_comments_searchPlaceholder: '按内容或作者搜索评论...',
    blog_comments_allStatus: '所有状态',
    blog_comments_allArticles: '所有文章',
    blog_comments_commentList: '评论列表',
    blog_comments_totalCommentsCount: '共 {count} 条评论',
    blog_comments_pendingModeration: '{count} 条待审核',
    blog_comments_author: '作者',
    blog_comments_email: '邮箱',
    blog_comments_content: '内容',
    blog_comments_article: '文章',
    blog_comments_createdAt: '创建时间',
    blog_comments_ipAddress: 'IP地址',
    blog_comments_actions: '操作',
    blog_comments_approve: '批准',
    blog_comments_reject: '拒绝',
    blog_comments_edit: '编辑',
    blog_comments_delete: '删除',
    blog_comments_viewArticle: '查看文章',
    blog_comments_reply: '回复',
    blog_comments_commentApproved: '评论批准成功',
    blog_comments_approveFailed: '批准评论失败',
    blog_comments_commentRejected: '评论拒绝成功',
    blog_comments_rejectFailed: '拒绝评论失败',
    blog_comments_commentDeleted: '评论删除成功',
    blog_comments_deleteFailed: '删除评论失败',
    blog_comments_loadFailed: '加载评论失败',
    blog_comments_deleteConfirm: '确定要删除此评论吗？此操作无法撤销。',
    blog_comments_moderationTips: '评论审核提示',
    blog_comments_tip1: '定期审核待处理评论以保持用户参与度',
    blog_comments_tip2: '标记明显的垃圾评论以帮助改进自动过滤',
    blog_comments_tip3: '考虑回复建设性评论以建立社区',
    blog_comments_tip4: '检查IP地址和用户代理以发现可疑模式',
    blog_comments_tip5: '使用搜索功能查找特定用户的评论',
    blog_comments_showingComments:
      '显示第 1 到 {current} 条评论，共 {total} 条',
    blog_comments_unknownArticle: '未知文章',
    blog_comments_untitled: '无标题',
  },
  ja: {
    dashboard: 'ダッシュボード',
    users: 'ユーザー管理',
    admin: '管理者アカウント',
    products: '商品',
    categories: 'カテゴリ',
    actSection: 'アクティブセクション',
    banners: 'バナー',
    groups: 'グループ購入',
    orders: '注文と配送',
    kyc: 'KYCレビュー',
    address: '住所管理',
    marketing: 'マーケティング',
    finance: 'ファイナンスセンター',
    finance_page: 'ファイナンス',
    paymentChannels: '支払いチャネル',
    logout: 'ログアウト',
    revenue: '総収入',
    activeUsers: 'アクティブユーザー',
    newOrders: '新規注文',
    add: '新規追加',
    edit: '編集',
    delete: '削除',
    save: '保存',
    cancel: 'キャンセル',
    search: '検索...',
    status: 'ステータス',
    actions: '操作',
    kyc_pending: 'KYC保留',
    notifications: '通知',
    analytics: 'データ分析',
    operationLogs: '操作ログ',
    roles: 'ロール管理',
    im: 'カスタマーサービス',
    supportChannels: 'サポートチャネル',
    ads: '広告',
    flashSale: 'フラッシュセール',
    loginLogs: 'ログインログ',
    luckyDraw: 'ラッキードロー',
    settings: 'システム設定',
    pendingApplications: '保留中の申請',

    // Blog Translation Progress Page
    blog_translation_pageTitle: '翻訳進捗モニター',
    blog_translation_pageSubtitle:
      'ブログコンテンツの翻訳進捗とステータスをリアルタイムで監視します',
    blog_translation_autoRefreshOn: '自動更新中',
    blog_translation_autoRefreshOff: '自動更新を有効にする',
    blog_translation_manualRefresh: '手動更新',
    blog_translation_overallProgress: '全体の進捗',
    blog_translation_completed: '完了',
    blog_translation_inProgress: '進行中',
    blog_translation_failed: '失敗',
    blog_translation_completedItems: '{completed} / {total} 件完了',
    blog_translation_articleTranslation: '記事翻訳',
    blog_translation_categoryTranslation: 'カテゴリ翻訳',
    blog_translation_tagTranslation: 'タグ翻訳',
    blog_translation_queueStatus: 'キューステータス',
    blog_translation_timeInfo: '時間情報',
    blog_translation_startTime: '開始時間',
    blog_translation_notStarted: '未開始',
    blog_translation_elapsedTime: '経過時間',
    blog_translation_estimatedCompletion: '完了見込み',
    blog_translation_unknown: '不明',
    blog_translation_pendingArticlesTitle: '🔍 保留中の記事 ({lang})',
    blog_translation_pendingArticlesDescription:
      '{count} 件の記事が {lang} 翻訳を保留中',
    blog_translation_allArticlesTranslated: 'すべての記事が翻訳済み',
    blog_translation_allArticlesTranslatedDesc:
      '言語 ({lang}) のすべての記事に翻訳があります',
    blog_translation_statusCompleted: '完了',
    blog_translation_statusProcessing: '処理中 {progress}%',
    blog_translation_statusQueued: 'キュー待ち',
    blog_translation_statusFailed: '失敗',
    blog_translation_statusUntranslated: '未翻訳',
    blog_translation_translateButton: '翻訳',
    blog_translation_activeJobsTitle: '⚡ 活動中の翻訳ジョブ ({count})',
    blog_translation_noActiveJobs: '活動中の翻訳ジョブはありません',
    blog_translation_typeArticle: '記事',
    blog_translation_typeCategory: 'カテゴリ',
    blog_translation_typeTag: 'タグ',
    blog_translation_issuesDetectionTitle: '🔍 翻訳問題検出',
    blog_translation_targetLanguage: 'ターゲット言語',
    blog_translation_recheck: '再チェック',
    blog_translation_selectAll: 'すべて選択',
    blog_translation_deselectAll: '選択解除',
    blog_translation_fixAll: 'すべて修正',
    blog_translation_fixSelected: '選択を修正 ({count})',
    blog_translation_issuesFound:
      '{count} 件の記事で翻訳の問題が見つかりました',
    blog_translation_articleTitle: '記事タイトル',
    blog_translation_issueType: '問題タイプ',
    blog_translation_severity: '重要度',
    blog_translation_issueTitleNotTranslated: 'タイトルが未翻訳',
    blog_translation_issueContentIncomplete: '内容が不完全',
    blog_translation_issueNotTranslated: '未翻訳',
    blog_translation_issueFailed: '翻訳に失敗しました',
    blog_translation_severityHigh: '高',
    blog_translation_severityMedium: '中',
    blog_translation_severityLow: '低',
    blog_translation_fixSingle: '修正',
    blog_translation_noIssuesFound: '翻訳の問題は見つかりませんでした',
    blog_translation_noIssuesFoundDesc:
      '言語 ({lang}) のすべての記事は正しく翻訳されています',
    blog_translation_jobHistoryTitle: '📋 翻訳ジョブ履歴',
    blog_translation_filter: 'フィルター',
    blog_translation_showOnlyActive:
      'アクティブなジョブのみ表示 (QUEUED/PROCESSING)',
    blog_translation_perPage: 'ページ当たり',
    blog_translation_perPageItems: '{count} 件',
    blog_translation_prevPage: '前へ',
    blog_translation_currentPage: 'ページ {page}',
    blog_translation_nextPage: '次へ',
    blog_translation_name: '名前',
    blog_translation_type: 'タイプ',
    blog_translation_targetLang: 'ターゲット',
    blog_translation_status: 'ステータス',
    blog_translation_progress: '進捗',
    blog_translation_createdAt: '作成日時',
    blog_translation_errorMsg: 'エラー',
    blog_translation_totalRecords:
      '合計 {total} 件、ページ {page} / {totalPages}',
    blog_translation_noJobRecords: 'ジョブ記録はありません',
    blog_translation_liveJobsTitle: 'ライブジョブキュー',
    blog_translation_activeJobs: 'アクティブジョブ ({count})',
    blog_translation_waitingJobs: '待機中 ({count})',
    blog_translation_failedJobs: '失敗したジョブ ({count})',
    blog_translation_moreWaitingJobs: '{count} 件のジョブが待機中',
    blog_translation_retry: '再試行',
    blog_translation_moreFailedJobs: '{count} 件の失敗ジョブ',
    blog_translation_noLiveJobs: 'キューにアクティブなジョブはありません',
    blog_translation_failedJobsAlertTitle: '失敗したジョブが検出されました',
    blog_translation_failedJobsAlertDesc:
      '{count} 件の翻訳ジョブが失敗しました。失敗ジョブリストを確認してください。',
    blog_translation_notStartedAlertTitle: '翻訳が開始されていません',
    blog_translation_notStartedAlertDesc:
      'すべての翻訳ジョブが待機中です。キューステータスを確認してください。',
    blog_translation_completedAlertTitle: '翻訳完了',
    blog_translation_completedAlertDesc:
      'すべての翻訳ジョブが正常に完了しました！',
    blog_translation_loadFailedTitle: '読み込み失敗',
    blog_translation_loadFailedDesc: '翻訳進捗データの読み込みに失敗しました',
    blog_translation_retryButton: '再試行',
    blog_translation_batchFixStarted:
      'バッチ修正を開始しました。{count} 件のジョブをキューに追加しました',
    blog_translation_batchFixFailed:
      'バッチ修正に失敗しました。後でもう一度お試しください',
    blog_translation_batchFixNetworkError:
      'バッチ修正に失敗しました。ネットワーク接続を確認してください',
    blog_translation_seconds: '0秒',
    blog_translation_progressWithPercent: '進捗: {progress}%',
    blog_translation_waiting: '待機中...',
    blog_translation_unknownError: '不明なエラー',
    blog_article_translationRequestSent:
      '翻訳リクエストが送信されました。自動的に更新されます',
    blog_article_translationFailed:
      '翻訳に失敗しました。後でもう一度お試しください',
    blog_article_retranslate: '再翻訳',
    blog_article_autoTranslateAfterSave: '保存後に英語版を自動翻訳',

    // Blog Dashboard Page
    blog_dashboard_pageTitle: 'ブログ管理',
    blog_dashboard_pageDescription:
      'ブログ記事、カテゴリ、タグ、およびコメントを管理します',
    blog_dashboard_writeNewArticle: '新しい記事を書く',
    blog_dashboard_totalArticles: '記事総数',
    blog_dashboard_categories: 'カテゴリ',
    blog_dashboard_tags: 'タグ',
    blog_dashboard_pendingComments: '保留中のコメント',
    blog_dashboard_recentArticles: '最近の記事',
    blog_dashboard_viewAll: 'すべて表示',
    blog_dashboard_article: '記事',
    blog_dashboard_status: 'ステータス',
    blog_dashboard_views: '閲覧数',
    blog_dashboard_comments: 'コメント',
    blog_dashboard_published: '公開済み',
    blog_dashboard_notPublished: '未公開',
    blog_dashboard_topPerformingArticles: '上位の記事',
    blog_dashboard_recentActivity: '最近の活動',
    blog_dashboard_blogSystemReady: 'ブログシステムが準備できました',
    blog_dashboard_backendApiReady:
      'バックエンドAPIが完全に実装され、コンテンツの作成が可能です',
    blog_dashboard_welcomeToBlogSystem: 'ブログシステムへようこそ',
    blog_dashboard_startCreatingFirstArticle: '最初の記事を作成しましょう',
    blog_dashboard_analyticsDashboardAdded:
      '分析ダッシュボードが追加されました',
    blog_dashboard_trackArticlePerformance:
      '記事のパフォーマンスとユーザー参加を追跡します',
    blog_dashboard_justNow: 'たった今',
    blog_dashboard_hoursAgo: '2時間前',
    blog_dashboard_loadingBlogDashboard: 'ブログダッシュボードを読み込み中...',
    blog_dashboard_numberOfPublishedArticles: '公開済み記事数',
    blog_dashboard_numberOfArticleCategories: '記事カテゴリ数',
    blog_dashboard_numberOfArticleTags: '記事タグ数',
    blog_dashboard_commentsAwaitingModeration: 'モデレーション待ちのコメント',

    // Blog Articles Page
    blog_articles_pageTitle: '記事管理',
    blog_articles_pageDescription: '記事の作成、編集、公開、削除を含む記事管理',
    blog_articles_newArticle: '新規作成',
    blog_articles_articleList: '記事一覧',
    blog_articles_search: '検索',
    blog_articles_searchPlaceholder: '記事タイトルまたは内容を検索...',
    blog_articles_status: 'ステータス',
    blog_articles_allStatus: 'すべてのステータス',
    blog_articles_published: '公開済み',
    blog_articles_draft: '下書き',
    blog_articles_archived: 'アーカイブ',
    blog_articles_category: 'カテゴリ',
    blog_articles_allCategories: 'すべてのカテゴリ',
    blog_articles_article: '記事',
    blog_articles_tags: 'タグ',
    blog_articles_metrics: '指標',
    blog_articles_views: '閲覧',
    blog_articles_comments: 'コメント',
    blog_articles_publishedDate: '公開日',
    blog_articles_notPublished: '未公開',
    blog_articles_actions: '操作',
    blog_articles_preview: 'プレビュー',
    blog_articles_edit: '編集',
    blog_articles_unpublish: '公開取り消し',
    blog_articles_publish: '公開',
    blog_articles_delete: '削除',
    blog_articles_deleteArticle: '記事を削除しますか？',
    blog_articles_deleteConfirm: '削除',
    blog_articles_cancel: 'キャンセル',
    blog_articles_articleDeleted: '記事が削除されました',
    blog_articles_deleteFailed: '記事の削除に失敗しました',
    blog_articles_publishArticle: '記事を公開しますか？',
    blog_articles_publishConfirm: '公開',
    blog_articles_articlePublished: '記事が公開されました',
    blog_articles_publishFailed: '記事の公開に失敗しました',
    blog_articles_unpublishArticle: '記事の公開を取り消しますか？',
    blog_articles_unpublishConfirm: '取り消し',
    blog_articles_articleUnpublished: '記事の公開が取り消されました',
    blog_articles_unpublishFailed: '記事の公開取り消しに失敗しました',
    blog_articles_actionCannotBeUndone: '⚠️ この操作は元に戻せません。',
    blog_articles_articleWillBePublic: '📢 記事は公開されます',
    blog_articles_articleWillBeHidden: '⚠️ 記事は非公開になります',
    blog_articles_articleDetails: '記事の詳細:',
    blog_articles_slug: 'スラッグ:',
    blog_articles_author: '作成者:',
    blog_articles_uncategorized: '未分類',
    blog_articles_admin: '管理者',
    blog_articles_min: '分',

    // Blog Categories Page
    blog_categories_pageTitle: 'カテゴリ管理',
    blog_categories_pageDescription: 'カテゴリを管理し、記事を整理します',
    blog_categories_newCategory: '新規カテゴリ',
    blog_categories_categoryList: 'カテゴリ一覧',
    blog_categories_search: '検索',
    blog_categories_searchPlaceholder: '名前または説明で検索...',
    blog_categories_name: '名前',
    blog_categories_slug: 'スラッグ',
    blog_categories_description: '説明',
    blog_categories_articles: '記事数',
    blog_categories_created: '作成日',
    blog_categories_actions: '操作',
    blog_categories_deleteCategory: 'カテゴリを削除しますか？',
    blog_categories_deleteConfirm: '削除',
    blog_categories_cancel: 'キャンセル',
    blog_categories_categoryDeleted: 'カテゴリが削除されました',
    blog_categories_deleteFailed: 'カテゴリの削除に失敗しました',
    blog_categories_actionCannotBeUndone: '⚠️ この操作は元に戻せません。',
    blog_categories_categoryDetails: 'カテゴリの詳細:',
    blog_categories_noDescription: '説明なし',
    blog_categories_uncategorized: '未分類',
    blog_categories_categoryUsageTips: 'カテゴリ使用のヒント',
    blog_categories_tip1: 'カテゴリは記事を論理的に整理するのに役立ちます',
    blog_categories_tip2: '各記事は1つのカテゴリのみ所属できます',
    blog_categories_tip3:
      'URLスラッグは小文字でハイフンを使用してください (例: "web-development")',
    blog_categories_tip4:
      '記事を含むカテゴリは削除できません - 先に記事を移動してください',
    blog_categories_thisCategoryContains:
      'このカテゴリには {count} 件の記事があります。',
    blog_categories_articlesWillBeMoved:
      'これらの記事は「未分類」に移動されます。',

    // Blog Tags Page
    blog_tags_pageTitle: 'タグ管理',
    blog_tags_pageDescription: 'タグを管理して記事を分類します',
    blog_tags_newTag: '新規タグ',
    blog_tags_tagList: 'タグ一覧',
    blog_tags_search: '検索',
    blog_tags_searchPlaceholder: '名前または説明でタグを検索...',
    blog_tags_totalTags: 'タグ総数',
    blog_tags_taggedArticles: 'タグ付き記事',
    blog_tags_totalTagsCount: '合計 {count} 個のタグ',
    blog_tags_name: '名前',
    blog_tags_slug: 'スラッグ',
    blog_tags_description: '説明',
    blog_tags_articles: '記事',
    blog_tags_uses: '使用回数',
    blog_tags_created: '作成日',
    blog_tags_actions: '操作',
    blog_tags_deleteTag: 'タグを削除しますか？',
    blog_tags_deleteConfirm: '削除',
    blog_tags_cancel: 'キャンセル',
    blog_tags_tagDeleted: 'タグが削除されました',
    blog_tags_deleteFailed: 'タグの削除に失敗しました',
    blog_tags_loadFailed: 'タグの読み込みに失敗しました',
    blog_tags_actionCannotBeUndone: 'この操作は元に戻せません。',
    blog_tags_loadingTags: 'タグを読み込み中...',
    blog_tags_noDescription: '説明なし',
    blog_tags_tagUsageTips: 'タグ使用のヒント',
    blog_tags_tip1: 'タグは記事を複数のトピックで分類するのに役立ちます',
    blog_tags_tip2: '各記事は複数のタグを持てます (カテゴリとは異なります)',
    blog_tags_tip3:
      '一般的なタグではなく、具体的で説明的なタグを使用してください',
    blog_tags_tip4: '人気のあるタグはブログで自動的に強調されます',
    blog_tags_tip5: '類似タグがある場合は統合できます',
    blog_tags_showingTags: '{current} / {total} 件を表示しています',

    // Blog Comments Page
    blog_comments_pageTitle: 'コメント管理',
    blog_comments_pageDescription: 'ブログ記事のコメントを審査および管理します',
    blog_comments_loadingComments: 'コメントを読み込み中...',
    blog_comments_totalComments: 'コメント総数',
    blog_comments_approved: '承認済み',
    blog_comments_pending: '保留中',
    blog_comments_spam: 'スパム',
    blog_comments_searchPlaceholder: '内容または作成者でコメントを検索...',
    blog_comments_allStatus: 'すべてのステータス',
    blog_comments_allArticles: 'すべての記事',
    blog_comments_commentList: 'コメント一覧',
    blog_comments_totalCommentsCount: '合計 {count} 件のコメント',
    blog_comments_pendingModeration: '{count} 件がモデレーション待ち',
    blog_comments_author: '作成者',
    blog_comments_email: 'メール',
    blog_comments_content: '内容',
    blog_comments_article: '記事',
    blog_comments_createdAt: '作成日時',
    blog_comments_ipAddress: 'IPアドレス',
    blog_comments_actions: '操作',
    blog_comments_approve: '承認',
    blog_comments_reject: '拒否',
    blog_comments_edit: '編集',
    blog_comments_delete: '削除',
    blog_comments_viewArticle: '記事を表示',
    blog_comments_reply: '返信',
    blog_comments_commentApproved: 'コメントが承認されました',
    blog_comments_approveFailed: 'コメント承認に失敗しました',
    blog_comments_commentRejected: 'コメントが拒否されました',
    blog_comments_rejectFailed: 'コメント拒否に失敗しました',
    blog_comments_commentDeleted: 'コメントが削除されました',
    blog_comments_deleteFailed: 'コメントの削除に失敗しました',
    blog_comments_loadFailed: 'コメントの読み込みに失敗しました',
    blog_comments_deleteConfirm:
      'このコメントを削除しますか？この操作は取り消せません。',
    blog_comments_moderationTips: 'コメントモデレーションのヒント',
    blog_comments_tip1:
      '定期的に保留中のコメントを確認してエンゲージメントを維持してください',
    blog_comments_tip2:
      '明らかなスパムはマークして自動フィルタ改善に役立ててください',
    blog_comments_tip3: '建設的なコメントには返信を検討してください',
    blog_comments_tip4:
      '疑わしいパターンを検出するためにIPアドレスとユーザーエージェントを確認してください',
    blog_comments_tip5:
      '特定のユーザーのコメントを見つけるには検索機能を使用してください',
    blog_comments_showingComments:
      '{current} / {total} 件のコメントを表示しています',
    blog_comments_unknownArticle: '不明な記事',
    blog_comments_untitled: 'タイトルなし',
  },
  ko: {
    dashboard: '대시보드',
    users: '사용자 관리',
    admin: '관리자 계정',
    products: '상품',
    categories: '카테고리',
    actSection: '활동 섹션',
    banners: '배너',
    groups: '공동구매',
    orders: '주문 및 배송',
    kyc: 'KYC 검토',
    address: '주소 관리',
    marketing: '마케팅',
    finance: '재무 센터',
    finance_page: '재무',
    paymentChannels: '결제 채널',
    logout: '로그아웃',
    revenue: '총 수익',
    activeUsers: '활성 사용자',
    newOrders: '신규 주문',
    add: '새로 추가',
    edit: '수정',
    delete: '삭제',
    save: '저장',
    cancel: '취소',
    search: '검색...',
    status: '상태',
    actions: '작업',
    kyc_pending: 'KYC 대기중',
    notifications: '알림',
    analytics: '데이터 분석',
    operationLogs: '작업 로그',
    roles: '역할 관리',
    im: '고객 지원',
    supportChannels: '지원 채널',
    ads: '광고',
    flashSale: '플래시 세일',
    loginLogs: '로그인 로그',
    luckyDraw: '럭키 드로우',
    settings: '시스템 설정',
    pendingApplications: '대기 중인 신청',

    // Blog Translation Progress Page
    blog_translation_pageTitle: '번역 진행 모니터',
    blog_translation_pageSubtitle:
      '블로그 콘텐츠 번역 진행 상황 및 상태를 실시간으로 모니터링합니다',
    blog_translation_autoRefreshOn: '자동 새로고침 중',
    blog_translation_autoRefreshOff: '자동 새로고침 활성화',
    blog_translation_manualRefresh: '수동 새로고침',
    blog_translation_overallProgress: '전체 진행률',
    blog_translation_completed: '완료',
    blog_translation_inProgress: '진행 중',
    blog_translation_failed: '실패',
    blog_translation_completedItems: '{completed} / {total} 항목 완료',
    blog_translation_articleTranslation: '기사 번역',
    blog_translation_categoryTranslation: '카테고리 번역',
    blog_translation_tagTranslation: '태그 번역',
    blog_translation_queueStatus: '대기열 상태',
    blog_translation_timeInfo: '시간 정보',
    blog_translation_startTime: '시작 시간',
    blog_translation_notStarted: '시작되지 않음',
    blog_translation_elapsedTime: '경과 시간',
    blog_translation_estimatedCompletion: '예상 완료',
    blog_translation_unknown: '알 수 없음',
    blog_translation_pendingArticlesTitle: '🔍 대기 중인 기사 ({lang})',
    blog_translation_pendingArticlesDescription:
      '{count}개의 기사가 {lang} 번역을 대기 중입니다',
    blog_translation_allArticlesTranslated: '모든 기사 번역 완료',
    blog_translation_allArticlesTranslatedDesc:
      '언어 ({lang})에 대한 모든 기사가 번역되어 있습니다',
    blog_translation_statusCompleted: '완료',
    blog_translation_statusProcessing: '처리 중 {progress}%',
    blog_translation_statusQueued: '대기 중',
    blog_translation_statusFailed: '실패',
    blog_translation_statusUntranslated: '미번역',
    blog_translation_translateButton: '번역',
    blog_translation_activeJobsTitle: '⚡ 활성 번역 작업 ({count})',
    blog_translation_noActiveJobs: '활성 번역 작업이 없습니다',
    blog_translation_typeArticle: '기사',
    blog_translation_typeCategory: '카테고리',
    blog_translation_typeTag: '태그',
    blog_translation_issuesDetectionTitle: '🔍 번역 문제 감지',
    blog_translation_targetLanguage: '대상 언어',
    blog_translation_recheck: '재검토',
    blog_translation_selectAll: '전체 선택',
    blog_translation_deselectAll: '선택 취소',
    blog_translation_fixAll: '모두 수정',
    blog_translation_fixSelected: '선택 항목 수정 ({count})',
    blog_translation_issuesFound:
      '{count}개의 기사에서 번역 문제가 발견되었습니다',
    blog_translation_articleTitle: '기사 제목',
    blog_translation_issueType: '문제 유형',
    blog_translation_severity: '심각도',
    blog_translation_issueTitleNotTranslated: '제목이 번역되지 않음',
    blog_translation_issueContentIncomplete: '내용 불완전',
    blog_translation_issueNotTranslated: '번역되지 않음',
    blog_translation_issueFailed: '번역 실패',
    blog_translation_severityHigh: '높음',
    blog_translation_severityMedium: '중간',
    blog_translation_severityLow: '낮음',
    blog_translation_fixSingle: '수정',
    blog_translation_noIssuesFound: '번역 문제가 없습니다',
    blog_translation_noIssuesFoundDesc:
      '언어 ({lang})의 모든 기사가 올바르게 번역되었습니다',
    blog_translation_jobHistoryTitle: '📋 번역 작업 히스토리',
    blog_translation_filter: '필터',
    blog_translation_showOnlyActive: '활성 작업만 표시 (QUEUED/PROCESSING)',
    blog_translation_perPage: '페이지 당',
    blog_translation_perPageItems: '{count} 항목',
    blog_translation_prevPage: '이전',
    blog_translation_currentPage: '페이지 {page}',
    blog_translation_nextPage: '다음',
    blog_translation_name: '이름',
    blog_translation_type: '유형',
    blog_translation_targetLang: '대상',
    blog_translation_status: '상태',
    blog_translation_progress: '진행률',
    blog_translation_createdAt: '생성일',
    blog_translation_errorMsg: '오류',
    blog_translation_totalRecords: '{total} 건, 페이지 {page} / {totalPages}',
    blog_translation_noJobRecords: '작업 기록이 없습니다',
    blog_translation_liveJobsTitle: '실시간 작업 큐',
    blog_translation_activeJobs: '활성 작업 ({count})',
    blog_translation_waitingJobs: '대기 중 ({count})',
    blog_translation_failedJobs: '실패 작업 ({count})',
    blog_translation_moreWaitingJobs: '{count} 개의 작업이 더 대기 중입니다',
    blog_translation_retry: '재시도',
    blog_translation_moreFailedJobs: '{count} 개의 실패 작업',
    blog_translation_noLiveJobs: '대기열에 활성 작업이 없습니다',
    blog_translation_failedJobsAlertTitle: '실패한 작업이 감지되었습니다',
    blog_translation_failedJobsAlertDesc:
      '{count} 개의 번역 작업이 실패했습니다. 실패한 작업 목록을 확인하세요.',
    blog_translation_notStartedAlertTitle: '번역이 시작되지 않았습니다',
    blog_translation_notStartedAlertDesc:
      '모든 번역 작업이 대기 중입니다. 대기열 상태를 확인하세요.',
    blog_translation_completedAlertTitle: '번역 완료',
    blog_translation_completedAlertDesc:
      '모든 번역 작업이 성공적으로 완료되었습니다!',
    blog_translation_loadFailedTitle: '로드 실패',
    blog_translation_loadFailedDesc: '번역 진행 데이터 로드에 실패했습니다',
    blog_translation_retryButton: '재시도',
    blog_translation_batchFixStarted:
      '배치 수정 시작, {count} 개의 작업이 큐에 추가됨',
    blog_translation_batchFixFailed: '배치 수정 실패, 나중에 다시 시도하세요',
    blog_translation_batchFixNetworkError:
      '배치 수정 실패, 네트워크 연결을 확인하세요',
    blog_translation_seconds: '0초',
    blog_translation_progressWithPercent: '진행: {progress}%',
    blog_translation_waiting: '대기 중...',
    blog_translation_unknownError: '알 수 없는 오류',
    blog_article_translationRequestSent:
      '번역 요청이 전송되었습니다. 자동으로 새로고침됩니다',
    blog_article_translationFailed:
      '번역에 실패했습니다. 나중에 다시 시도하세요',
    blog_article_retranslate: '재번역',
    blog_article_autoTranslateAfterSave: '저장 후 영어 버전을 자동 번역',

    // Blog Dashboard Page
    blog_dashboard_pageTitle: '블로그 관리',
    blog_dashboard_pageDescription:
      '블로그 게시물, 카테고리, 태그 및 댓글을 관리합니다',
    blog_dashboard_writeNewArticle: '새 게시물 작성',
    blog_dashboard_totalArticles: '총 게시물 수',
    blog_dashboard_categories: '카테고리',
    blog_dashboard_tags: '태그',
    blog_dashboard_pendingComments: '대기 중인 댓글',
    blog_dashboard_recentArticles: '최근 게시물',
    blog_dashboard_viewAll: '모두 보기',
    blog_dashboard_article: '게시물',
    blog_dashboard_status: '상태',
    blog_dashboard_views: '조회수',
    blog_dashboard_comments: '댓글',
    blog_dashboard_published: '게시됨',
    blog_dashboard_notPublished: '미게시',
    blog_dashboard_topPerformingArticles: '상위 게시물',
    blog_dashboard_recentActivity: '최근 활동',
    blog_dashboard_blogSystemReady: '블로그 시스템이 준비되었습니다',
    blog_dashboard_backendApiReady:
      '백엔드 API가 구현되어 콘텐츠 생성을 시작할 준비가 되었습니다',
    blog_dashboard_welcomeToBlogSystem: '블로그 시스템에 오신 것을 환영합니다',
    blog_dashboard_startCreatingFirstArticle: '첫 게시물을 작성해보세요',
    blog_dashboard_analyticsDashboardAdded: '분석 대시보드가 추가되었습니다',
    blog_dashboard_trackArticlePerformance: '게시물 성능 및 사용자 참여 추적',
    blog_dashboard_justNow: '방금',
    blog_dashboard_hoursAgo: '2시간 전',
    blog_dashboard_loadingBlogDashboard: '블로그 대시보드를 로드하는 중...',
    blog_dashboard_numberOfPublishedArticles: '게시된 게시물 수',
    blog_dashboard_numberOfArticleCategories: '게시물 카테고리 수',
    blog_dashboard_numberOfArticleTags: '게시물 태그 수',
    blog_dashboard_commentsAwaitingModeration: '모더레이션 대기 중인 댓글',

    // Blog Articles Page
    blog_articles_pageTitle: '게시물 관리',
    blog_articles_pageDescription: '게시물 생성, 편집, 게시 및 삭제 관리',
    blog_articles_newArticle: '새로 만들기',
    blog_articles_articleList: '게시물 목록',
    blog_articles_search: '검색',
    blog_articles_searchPlaceholder: '게시물 제목 또는 내용을 검색...',
    blog_articles_status: '상태',
    blog_articles_allStatus: '모든 상태',
    blog_articles_published: '게시됨',
    blog_articles_draft: '초안',
    blog_articles_archived: '보관됨',
    blog_articles_category: '카테고리',
    blog_articles_allCategories: '모든 카테고리',
    blog_articles_article: '게시물',
    blog_articles_tags: '태그',
    blog_articles_metrics: '지표',
    blog_articles_views: '조회수',
    blog_articles_comments: '댓글',
    blog_articles_publishedDate: '게시일',
    blog_articles_notPublished: '미게시',
    blog_articles_actions: '작업',
    blog_articles_preview: '미리보기',
    blog_articles_edit: '편집',
    blog_articles_unpublish: '게시 취소',
    blog_articles_publish: '게시',
    blog_articles_delete: '삭제',
    blog_articles_deleteArticle: '게시물을 삭제하시겠습니까?',
    blog_articles_deleteConfirm: '삭제',
    blog_articles_cancel: '취소',
    blog_articles_articleDeleted: '게시물이 삭제되었습니다',
    blog_articles_deleteFailed: '게시물 삭제에 실패했습니다',
    blog_articles_publishArticle: '게시물을 게시하시겠습니까?',
    blog_articles_publishConfirm: '게시',
    blog_articles_articlePublished: '게시물이 게시되었습니다',
    blog_articles_publishFailed: '게시물 게시에 실패했습니다',
    blog_articles_unpublishArticle: '게시물을 게시 취소하시겠습니까?',
    blog_articles_unpublishConfirm: '취소',
    blog_articles_articleUnpublished: '게시물 게시가 취소되었습니다',
    blog_articles_unpublishFailed: '게시물 게시 취소에 실패했습니다',
    blog_articles_actionCannotBeUndone: '⚠️ 이 작업은 되돌릴 수 없습니다.',
    blog_articles_articleWillBePublic: '📢 게시물이 공개됩니다',
    blog_articles_articleWillBeHidden: '⚠️ 게시물이 숨김 처리됩니다',
    blog_articles_articleDetails: '게시물 세부정보:',
    blog_articles_slug: '슬러그:',
    blog_articles_author: '작성자:',
    blog_articles_uncategorized: '미분류',
    blog_articles_admin: '관리자',
    blog_articles_min: '분',

    // Blog Categories Page
    blog_categories_pageTitle: '카테고리 관리',
    blog_categories_pageDescription: '카테고리를 관리하여 게시물을 정리합니다',
    blog_categories_newCategory: '새 카테고리',
    blog_categories_categoryList: '카테고리 목록',
    blog_categories_search: '검색',
    blog_categories_searchPlaceholder: '이름 또는 설명으로 검색...',
    blog_categories_name: '이름',
    blog_categories_slug: '슬러그',
    blog_categories_description: '설명',
    blog_categories_articles: '게시물 수',
    blog_categories_created: '생성일',
    blog_categories_actions: '작업',
    blog_categories_deleteCategory: '카테고리를 삭제하시겠습니까?',
    blog_categories_deleteConfirm: '삭제',
    blog_categories_cancel: '취소',
    blog_categories_categoryDeleted: '카테고리가 삭제되었습니다',
    blog_categories_deleteFailed: '카테고리 삭제에 실패했습니다',
    blog_categories_actionCannotBeUndone: '⚠️ 이 작업은 되돌릴 수 없습니다。',
    blog_categories_categoryDetails: '카테고리 세부정보:',
    blog_categories_noDescription: '설명 없음',
    blog_categories_uncategorized: '미분류',
    blog_categories_categoryUsageTips: '카테고리 사용 팁',
    blog_categories_tip1:
      '카테고리는 게시물을 논리적으로 구성하는 데 도움이 됩니다',
    blog_categories_tip2: '각 게시물은 하나의 카테고리에만 속할 수 있습니다',
    blog_categories_tip3:
      'URL 슬러그는 소문자와 하이픈을 사용하세요 (예: "web-development")',
    blog_categories_tip4:
      '게시물을 포함하는 카테고리는 삭제할 수 없습니다 - 먼저 게시물을 이동하세요',
    blog_categories_thisCategoryContains:
      '이 카테고리에는 {count} 개의 게시물이 있습니다。',
    blog_categories_articlesWillBeMoved:
      '이 게시물들은 "미분류"로 이동됩니다。',

    // Blog Tags Page
    blog_tags_pageTitle: '태그 관리',
    blog_tags_pageDescription: '태그를 관리하여 게시물을 분류합니다',
    blog_tags_newTag: '새 태그',
    blog_tags_tagList: '태그 목록',
    blog_tags_search: '검색',
    blog_tags_searchPlaceholder: '이름 또는 설명으로 태그 검색...',
    blog_tags_totalTags: '태그 총수',
    blog_tags_taggedArticles: '태그된 게시물',
    blog_tags_totalTagsCount: '총 {count} 개의 태그',
    blog_tags_name: '이름',
    blog_tags_slug: '슬러그',
    blog_tags_description: '설명',
    blog_tags_articles: '게시물',
    blog_tags_uses: '사용 횟수',
    blog_tags_created: '생성일',
    blog_tags_actions: '작업',
    blog_tags_deleteTag: '태그를 삭제하시겠습니까?',
    blog_tags_deleteConfirm: '삭제',
    blog_tags_cancel: '취소',
    blog_tags_tagDeleted: '태그가 삭제되었습니다',
    blog_tags_deleteFailed: '태그 삭제에 실패했습니다',
    blog_tags_loadFailed: '태그 로드에 실패했습니다',
    blog_tags_actionCannotBeUndone: '이 작업은 되돌릴 수 없습니다。',
    blog_tags_loadingTags: '태그를 로드하는 중...',
    blog_tags_noDescription: '설명 없음',
    blog_tags_tagUsageTips: '태그 사용 팁',
    blog_tags_tip1: '태그는 게시물을 여러 주제로 분류하는 데 도움이 됩니다',
    blog_tags_tip2:
      '각 게시물은 여러 태그를 가질 수 있습니다 (카테고리와 다름)',
    blog_tags_tip3: '일반적인 태그보다 구체적이고 설명적인 태그를 사용하세요',
    blog_tags_tip4: '인기 태그는 블로그에서 자동으로 강조됩니다',
    blog_tags_tip5: '유사한 태그는 병합할 수 있습니다',
    blog_tags_showingTags: '{current} / {total} 개 항목 표시',

    // Blog Comments Page
    blog_comments_pageTitle: '댓글 관리',
    blog_comments_pageDescription: '블로그 게시물의 댓글을 심사하고 관리합니다',
    blog_comments_loadingComments: '댓글을 로드하는 중...',
    blog_comments_totalComments: '댓글 총수',
    blog_comments_approved: '승인됨',
    blog_comments_pending: '대기 중',
    blog_comments_spam: '스팸',
    blog_comments_searchPlaceholder: '내용 또는 작성자로 댓글 검색...',
    blog_comments_allStatus: '모든 상태',
    blog_comments_allArticles: '모든 게시물',
    blog_comments_commentList: '댓글 목록',
    blog_comments_totalCommentsCount: '총 {count} 개의 댓글',
    blog_comments_pendingModeration: '{count} 개가 모더레이션 대기 중',
    blog_comments_author: '작성자',
    blog_comments_email: '이메일',
    blog_comments_content: '내용',
    blog_comments_article: '게시물',
    blog_comments_createdAt: '작성일',
    blog_comments_ipAddress: 'IP 주소',
    blog_comments_actions: '작업',
    blog_comments_approve: '승인',
    blog_comments_reject: '거부',
    blog_comments_edit: '편집',
    blog_comments_delete: '삭제',
    blog_comments_viewArticle: '게시물 보기',
    blog_comments_reply: '답글',
    blog_comments_commentApproved: '댓글이 승인되었습니다',
    blog_comments_approveFailed: '댓글 승인에 실패했습니다',
    blog_comments_commentRejected: '댓글이 거부되었습니다',
    blog_comments_rejectFailed: '댓글 거부에 실패했습니다',
    blog_comments_commentDeleted: '댓글이 삭제되었습니다',
    blog_comments_deleteFailed: '댓글 삭제에 실패했습니다',
    blog_comments_loadFailed: '댓글 로드에 실패했습니다',
    blog_comments_deleteConfirm:
      '이 댓글을 삭제하시겠습니까? 이 작업은 취소할 수 없습니다。',
    blog_comments_moderationTips: '댓글 모더레이션 팁',
    blog_comments_tip1:
      '보류 중인 댓글을 정기적으로 검토하여 참여도를 유지하세요',
    blog_comments_tip2: '명백한 스팸을 표시하여 자동 필터 개선에 도움을 주세요',
    blog_comments_tip3: '건설적인 댓글에는 답글을 고려하세요',
    blog_comments_tip4:
      '의심스러운 패턴을 찾기 위해 IP 주소와 사용자 에이전트를 확인하세요',
    blog_comments_tip5: '특정 사용자의 댓글을 찾으려면 검색 기능을 사용하세요',
    blog_comments_showingComments: '{current} / {total} 개의 댓글을 표시합니다',
    blog_comments_unknownArticle: '알 수 없는 게시물',
    blog_comments_untitled: '제목 없음',
  },
  fr: {
    dashboard: 'Tableau de bord',
    users: 'Gestion des utilisateurs',
    admin: 'Comptes administrateurs',
    products: 'Produits',
    categories: 'Catégories',
    actSection: 'Sections actives',
    banners: 'Bannières',
    groups: 'Achat groupé',
    orders: 'Commandes et livraison',
    kyc: 'Vérification KYC',
    address: 'Adresses',
    marketing: 'Marketing',
    finance: 'Centre financier',
    finance_page: 'Finance',
    paymentChannels: 'Canaux de paiement',
    logout: 'Déconnexion',
    revenue: 'Revenu total',
    activeUsers: 'Utilisateurs actifs',
    newOrders: 'Nouvelles commandes',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    search: 'Rechercher...',
    status: 'Statut',
    actions: 'Actions',
    kyc_pending: 'KYC en attente',
    notifications: 'Notifications',
    analytics: 'Analyse des données',
    operationLogs: "Journaux d'opérations",
    roles: 'Gestion des rôles',
    im: 'Service client',
    supportChannels: 'Canaux de support',
    ads: 'Publicités',
    flashSale: 'Vente flash',
    loginLogs: 'Journaux de connexion',
    luckyDraw: 'Tirage au sort',
    settings: 'Configuration système',
    pendingApplications: 'Demandes en attente',

    // Blog Translation Progress Page
    blog_translation_pageTitle: 'Moniteur de progression des traductions',
    blog_translation_pageSubtitle:
      'Surveillance en temps réel de la progression et du statut des traductions de contenu du blog',
    blog_translation_autoRefreshOn: 'Actualisation automatique',
    blog_translation_autoRefreshOff: "Activer l'actualisation automatique",
    blog_translation_manualRefresh: 'Actualisation manuelle',
    blog_translation_overallProgress: 'Progression globale',
    blog_translation_completed: 'Terminé',
    blog_translation_inProgress: 'En cours',
    blog_translation_failed: 'Échoué',
    blog_translation_completedItems: '{completed} / {total} éléments terminés',
    blog_translation_articleTranslation: "Traduction d'article",
    blog_translation_categoryTranslation: 'Traduction de catégorie',
    blog_translation_tagTranslation: 'Traduction de tag',
    blog_translation_queueStatus: 'Statut de la file',
    blog_translation_timeInfo: 'Informations temporelles',
    blog_translation_startTime: 'Heure de début',
    blog_translation_notStarted: 'Non commencé',
    blog_translation_elapsedTime: 'Écoulé',
    blog_translation_estimatedCompletion: "Estimation d'achèvement",
    blog_translation_unknown: 'Inconnu',
    blog_translation_pendingArticlesTitle: '🔍 Articles en attente ({lang})',
    blog_translation_pendingArticlesDescription:
      '{count} articles en attente de traduction en {lang}',
    blog_translation_allArticlesTranslated: 'Tous les articles traduits',
    blog_translation_allArticlesTranslatedDesc:
      'Tous les articles pour la langue ({lang}) ont des traductions',
    blog_translation_statusCompleted: 'Terminé',
    blog_translation_statusProcessing: 'Traitement {progress}%',
    blog_translation_statusQueued: 'En file',
    blog_translation_statusFailed: 'Échoué',
    blog_translation_statusUntranslated: 'Non traduits',
    blog_translation_translateButton: 'Traduire',
    blog_translation_activeJobsTitle:
      '⚡ Travaux de traduction actifs ({count})',
    blog_translation_noActiveJobs: 'Aucun travail de traduction actif',
    blog_translation_typeArticle: 'Article',
    blog_translation_typeCategory: 'Catégorie',
    blog_translation_typeTag: 'Tag',
    blog_translation_issuesDetectionTitle:
      '🔍 Détection des problèmes de traduction',
    blog_translation_targetLanguage: 'Langue cible',
    blog_translation_recheck: 'Vérifier à nouveau',
    blog_translation_selectAll: 'Tout sélectionner',
    blog_translation_deselectAll: 'Tout désélectionner',
    blog_translation_fixAll: 'Corriger tout',
    blog_translation_fixSelected: 'Corriger la sélection ({count})',
    blog_translation_issuesFound:
      '{count} articles présentant des problèmes de traduction trouvés',
    blog_translation_articleTitle: "Titre de l'article",
    blog_translation_issueType: 'Type de problème',
    blog_translation_severity: 'Gravité',
    blog_translation_issueTitleNotTranslated: 'Titre non traduit',
    blog_translation_issueContentIncomplete: 'Contenu incomplet',
    blog_translation_issueNotTranslated: 'Non traduit',
    blog_translation_issueFailed: 'Échec de la traduction',
    blog_translation_severityHigh: 'Élevée',
    blog_translation_severityMedium: 'Moyenne',
    blog_translation_severityLow: 'Faible',
    blog_translation_fixSingle: 'Corriger',
    blog_translation_noIssuesFound: 'Aucun problème de traduction trouvé',
    blog_translation_noIssuesFoundDesc:
      'Tous les articles pour la langue ({lang}) sont correctement traduits',
    blog_translation_jobHistoryTitle: '📋 Historique des travaux de traduction',
    blog_translation_filter: 'Filtrer',
    blog_translation_showOnlyActive:
      'Afficher uniquement les travaux actifs (QUEUED/PROCESSING)',
    blog_translation_perPage: 'Par page',
    blog_translation_perPageItems: '{count} éléments',
    blog_translation_prevPage: 'Précédent',
    blog_translation_currentPage: 'Page {page}',
    blog_translation_nextPage: 'Suivant',
    blog_translation_name: 'Nom',
    blog_translation_type: 'Type',
    blog_translation_targetLang: 'Cible',
    blog_translation_status: 'Statut',
    blog_translation_progress: 'Progression',
    blog_translation_createdAt: 'Créé le',
    blog_translation_errorMsg: 'Erreur',
    blog_translation_totalRecords:
      '{total} enregistrements au total, page {page} / {totalPages}',
    blog_translation_noJobRecords: 'Aucun enregistrement de travail',
    blog_translation_liveJobsTitle: 'File des travaux en direct',
    blog_translation_activeJobs: 'Travaux actifs ({count})',
    blog_translation_waitingJobs: 'Travaux en attente ({count})',
    blog_translation_failedJobs: 'Travaux échoués ({count})',
    blog_translation_moreWaitingJobs:
      '{count} travaux supplémentaires en attente',
    blog_translation_retry: 'Réessayer',
    blog_translation_moreFailedJobs: '{count} travaux échoués supplémentaires',
    blog_translation_noLiveJobs: 'Aucun travail actif dans la file',
    blog_translation_failedJobsAlertTitle: 'Travaux échoués détectés',
    blog_translation_failedJobsAlertDesc:
      '{count} travaux de traduction ont échoué, vérifiez la liste des travaux échoués.',
    blog_translation_notStartedAlertTitle: 'Traduction non commencée',
    blog_translation_notStartedAlertDesc:
      "Tous les travaux de traduction sont en attente, vérifiez l'état de la file.",
    blog_translation_completedAlertTitle: 'Traduction terminée',
    blog_translation_completedAlertDesc:
      'Tous les travaux de traduction se sont terminés avec succès !',
    blog_translation_loadFailedTitle: 'Échec du chargement',
    blog_translation_loadFailedDesc:
      'Échec du chargement des données de progression de traduction',
    blog_translation_retryButton: 'Réessayer',
    blog_translation_batchFixStarted:
      'Correction par lot démarrée, {count} travaux ajoutés à la file',
    blog_translation_batchFixFailed:
      'Échec de la correction par lot, veuillez réessayer plus tard',
    blog_translation_batchFixNetworkError:
      'Échec de la correction par lot, vérifiez la connexion réseau',
    blog_translation_seconds: '0s',
    blog_translation_progressWithPercent: 'Progression : {progress}%',
    blog_translation_waiting: 'En attente...',
    blog_translation_unknownError: 'Erreur inconnue',
    blog_article_translationRequestSent:
      'Demande de traduction envoyée, la page se rafraîchira automatiquement',
    blog_article_translationFailed:
      'La traduction a échoué, veuillez réessayer plus tard',
    blog_article_retranslate: 'Retraduire',
    blog_article_autoTranslateAfterSave:
      'Traduire automatiquement la version anglaise après la sauvegarde',

    // Blog Dashboard Page
    blog_dashboard_pageTitle: 'Gestion du blog',
    blog_dashboard_pageDescription:
      'Gérer les articles, catégories, tags et commentaires du blog',
    blog_dashboard_writeNewArticle: 'Écrire un nouvel article',
    blog_dashboard_totalArticles: "Nombre total d'articles",
    blog_dashboard_categories: 'Catégories',
    blog_dashboard_tags: 'Tags',
    blog_dashboard_pendingComments: 'Commentaires en attente',
    blog_dashboard_recentArticles: 'Articles récents',
    blog_dashboard_viewAll: 'Tout voir',
    blog_dashboard_article: 'Article',
    blog_dashboard_status: 'Statut',
    blog_dashboard_views: 'Vues',
    blog_dashboard_comments: 'Commentaires',
    blog_dashboard_published: 'Publié',
    blog_dashboard_notPublished: 'Non publié',
    blog_dashboard_topPerformingArticles: 'Articles les plus performants',
    blog_dashboard_recentActivity: 'Activité récente',
    blog_dashboard_blogSystemReady: 'Le système de blog est prêt',
    blog_dashboard_backendApiReady:
      "L'API backend est entièrement implémentée, prête à créer du contenu",
    blog_dashboard_welcomeToBlogSystem: 'Bienvenue dans le système de blog',
    blog_dashboard_startCreatingFirstArticle:
      'Commencez à créer votre premier article',
    blog_dashboard_analyticsDashboardAdded: 'Tableau de bord analytique ajouté',
    blog_dashboard_trackArticlePerformance:
      "Suivre les performances des articles et l'engagement des utilisateurs",
    blog_dashboard_justNow: "À l'instant",
    blog_dashboard_hoursAgo: 'Il y a 2 heures',
    blog_dashboard_loadingBlogDashboard:
      'Chargement du tableau de bord du blog...',
    blog_dashboard_numberOfPublishedArticles: "Nombre d'articles publiés",
    blog_dashboard_numberOfArticleCategories: "Nombre de catégories d'articles",
    blog_dashboard_numberOfArticleTags: "Nombre de tags d'articles",
    blog_dashboard_commentsAwaitingModeration:
      'Commentaires en attente de modération',

    // Blog Articles Page
    blog_articles_pageTitle: 'Gestion des articles',
    blog_articles_pageDescription:
      "Gérer les articles du blog, y compris la création, l'édition, la publication et la suppression",
    blog_articles_newArticle: 'Nouvel article',
    blog_articles_articleList: 'Liste des articles',
    blog_articles_search: 'Recherche',
    blog_articles_searchPlaceholder:
      "Rechercher des titres ou du contenu d'articles...",
    blog_articles_status: 'Statut',
    blog_articles_allStatus: 'Tous les statuts',
    blog_articles_published: 'Publié',
    blog_articles_draft: 'Brouillon',
    blog_articles_archived: 'Archivé',
    blog_articles_category: 'Catégorie',
    blog_articles_allCategories: 'Toutes les catégories',
    blog_articles_article: 'Article',
    blog_articles_tags: 'Tags',
    blog_articles_metrics: 'Métriques',
    blog_articles_views: 'vues',
    blog_articles_comments: 'commentaires',
    blog_articles_publishedDate: 'Date de publication',
    blog_articles_notPublished: 'Non publié',
    blog_articles_actions: 'Actions',
    blog_articles_preview: 'Aperçu',
    blog_articles_edit: 'Modifier',
    blog_articles_unpublish: 'Retirer la publication',
    blog_articles_publish: 'Publier',
    blog_articles_delete: 'Supprimer',
    blog_articles_deleteArticle: "Supprimer l'article ?",
    blog_articles_deleteConfirm: 'Supprimer',
    blog_articles_cancel: 'Annuler',
    blog_articles_articleDeleted: 'Article supprimé avec succès',
    blog_articles_deleteFailed: "Échec de la suppression de l'article",
    blog_articles_publishArticle: "Publier l'article ?",
    blog_articles_publishConfirm: 'Publier',
    blog_articles_articlePublished: 'Article publié avec succès',
    blog_articles_publishFailed: "Échec de la publication de l'article",
    blog_articles_unpublishArticle: "Retirer la publication de l'article ?",
    blog_articles_unpublishConfirm: 'Retirer',
    blog_articles_articleUnpublished: "Publication de l'article annulée",
    blog_articles_unpublishFailed: "Échec de l'annulation de la publication",
    blog_articles_actionCannotBeUndone:
      '⚠️ Cette action ne peut pas être annulée.',
    blog_articles_articleWillBePublic: "📢 L'article sera public",
    blog_articles_articleWillBeHidden: "⚠️ L'article sera masqué",
    blog_articles_articleDetails: "Détails de l'article :",
    blog_articles_slug: 'Slug :',
    blog_articles_author: 'Auteur :',
    blog_articles_uncategorized: 'Non classé',
    blog_articles_admin: 'Admin',
    blog_articles_min: 'min',

    // Blog Categories Page
    blog_categories_pageTitle: 'Gestion des catégories',
    blog_categories_pageDescription:
      "Gérer les catégories d'articles pour organiser le contenu",
    blog_categories_newCategory: 'Nouvelle catégorie',
    blog_categories_categoryList: 'Liste des catégories',
    blog_categories_search: 'Recherche',
    blog_categories_searchPlaceholder: 'Rechercher par nom ou description...',
    blog_categories_name: 'Nom',
    blog_categories_slug: 'Slug',
    blog_categories_description: 'Description',
    blog_categories_articles: 'Articles',
    blog_categories_created: 'Créé',
    blog_categories_actions: 'Actions',
    blog_categories_deleteCategory: 'Supprimer la catégorie ?',
    blog_categories_deleteConfirm: 'Supprimer',
    blog_categories_cancel: 'Annuler',
    blog_categories_categoryDeleted: 'Catégorie supprimée avec succès',
    blog_categories_deleteFailed: 'Échec de la suppression de la catégorie',
    blog_categories_actionCannotBeUndone:
      '⚠️ Cette action ne peut pas être annulée.',
    blog_categories_categoryDetails: 'Détails de la catégorie :',
    blog_categories_noDescription: 'Aucune description',
    blog_categories_uncategorized: 'Non classé',
    blog_categories_categoryUsageTips: "Conseils d'utilisation des catégories",
    blog_categories_tip1:
      'Les catégories aident à organiser les articles en groupes logiques',
    blog_categories_tip2:
      "Chaque article ne peut appartenir qu'à une seule catégorie",
    blog_categories_tip3:
      'Les slugs d\'URL doivent être en minuscules et utiliser des tirets (ex : "web-development")',
    blog_categories_tip4:
      "Les catégories contenant des articles ne peuvent pas être supprimées - déplacez d'abord les articles",
    blog_categories_thisCategoryContains:
      'Cette catégorie contient {count} articles.',
    blog_categories_articlesWillBeMoved:
      'Ces articles seront déplacés vers "Non classé".',

    // Blog Tags Page
    blog_tags_pageTitle: 'Gestion des tags',
    blog_tags_pageDescription: 'Gérer les tags pour classer les articles',
    blog_tags_newTag: 'Nouveau tag',
    blog_tags_tagList: 'Liste des tags',
    blog_tags_search: 'Recherche',
    blog_tags_searchPlaceholder:
      'Rechercher des tags par nom ou description...',
    blog_tags_totalTags: 'Nombre total de tags',
    blog_tags_taggedArticles: 'Articles taggés',
    blog_tags_totalTagsCount: 'Total {count} tags',
    blog_tags_name: 'Nom',
    blog_tags_slug: 'Slug',
    blog_tags_description: 'Description',
    blog_tags_articles: 'Articles',
    blog_tags_uses: 'Utilisations',
    blog_tags_created: 'Créé',
    blog_tags_actions: 'Actions',
    blog_tags_deleteTag: 'Supprimer le tag ?',
    blog_tags_deleteConfirm: 'Supprimer',
    blog_tags_cancel: 'Annuler',
    blog_tags_tagDeleted: 'Tag supprimé avec succès',
    blog_tags_deleteFailed: 'Échec de la suppression du tag',
    blog_tags_loadFailed: 'Échec du chargement des tags',
    blog_tags_actionCannotBeUndone: 'Cette action ne peut pas être annulée.',
    blog_tags_loadingTags: 'Chargement des tags...',
    blog_tags_noDescription: 'Aucune description',
    blog_tags_tagUsageTips: "Conseils d'utilisation des tags",
    blog_tags_tip1:
      'Les tags aident à classer les articles par plusieurs sujets',
    blog_tags_tip2:
      'Chaque article peut avoir plusieurs tags (contrairement aux catégories)',
    blog_tags_tip3:
      'Utilisez des tags spécifiques et descriptifs plutôt que des tags génériques',
    blog_tags_tip4:
      'Les tags populaires sont automatiquement mis en évidence dans le blog',
    blog_tags_tip5: 'Les tags similaires peuvent être fusionnés',
    blog_tags_showingTags: 'Affichage de {current} sur {total} tags',

    // Blog Comments Page
    blog_comments_pageTitle: 'Gestion des commentaires',
    blog_comments_pageDescription:
      'Modérer et gérer les commentaires des articles de blog',
    blog_comments_loadingComments: 'Chargement des commentaires...',
    blog_comments_totalComments: 'Nombre de commentaires',
    blog_comments_approved: 'Approuvé',
    blog_comments_pending: 'En attente',
    blog_comments_spam: 'Spam',
    blog_comments_searchPlaceholder:
      'Rechercher des commentaires par contenu ou auteur...',
    blog_comments_allStatus: 'Tous les statuts',
    blog_comments_allArticles: 'Tous les articles',
    blog_comments_commentList: 'Liste des commentaires',
    blog_comments_totalCommentsCount: 'Total {count} commentaires',
    blog_comments_pendingModeration: '{count} en attente de modération',
    blog_comments_author: 'Auteur',
    blog_comments_email: 'Email',
    blog_comments_content: 'Contenu',
    blog_comments_article: 'Article',
    blog_comments_createdAt: 'Créé le',
    blog_comments_ipAddress: 'Adresse IP',
    blog_comments_actions: 'Actions',
    blog_comments_approve: 'Approuver',
    blog_comments_reject: 'Rejeter',
    blog_comments_edit: 'Modifier',
    blog_comments_delete: 'Supprimer',
    blog_comments_viewArticle: "Voir l'article",
    blog_comments_reply: 'Répondre',
    blog_comments_commentApproved: 'Commentaire approuvé avec succès',
    blog_comments_approveFailed: "Échec de l'approbation du commentaire",
    blog_comments_commentRejected: 'Commentaire rejeté avec succès',
    blog_comments_rejectFailed: 'Échec du rejet du commentaire',
    blog_comments_commentDeleted: 'Commentaire supprimé avec succès',
    blog_comments_deleteFailed: 'Échec de la suppression du commentaire',
    blog_comments_loadFailed: 'Échec du chargement des commentaires',
    blog_comments_deleteConfirm:
      'Voulez-vous vraiment supprimer ce commentaire ? Cette action ne peut pas être annulée.',
    blog_comments_moderationTips: 'Conseils de modération des commentaires',
    blog_comments_tip1:
      "Vérifiez régulièrement les commentaires en attente pour maintenir l'engagement",
    blog_comments_tip2:
      'Marquez les spams évidents pour aider à améliorer le filtrage automatique',
    blog_comments_tip3:
      'Envisagez de répondre aux commentaires constructifs pour construire la communauté',
    blog_comments_tip4:
      'Vérifiez les adresses IP et les user agents pour détecter les schémas suspects',
    blog_comments_tip5:
      "Utilisez la recherche pour trouver les commentaires d'un utilisateur spécifique",
    blog_comments_showingComments:
      'Affichage de {current} sur {total} commentaires',
    blog_comments_unknownArticle: 'Article inconnu',
    blog_comments_untitled: 'Sans titre',
  },
  de: {
    dashboard: 'Dashboard',
    users: 'Benutzerverwaltung',
    admin: 'Administrator-Konten',
    products: 'Produkte',
    categories: 'Kategorien',
    actSection: 'Aktionsabschnitte',
    banners: 'Banner',
    groups: 'Gruppenkauf',
    orders: 'Bestellungen & Lieferung',
    kyc: 'KYC-Prüfung',
    address: 'Adressen',
    marketing: 'Marketing',
    finance: 'Finanzzentrum',
    finance_page: 'Finanzen',
    paymentChannels: 'Zahlungskanäle',
    logout: 'Abmelden',
    revenue: 'Gesamteinnahmen',
    activeUsers: 'Aktive Nutzer',
    newOrders: 'Neue Bestellungen',
    add: 'Neu hinzufügen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    search: 'Suche...',
    status: 'Status',
    actions: 'Aktionen',
    kyc_pending: 'KYC ausstehend',
    notifications: 'Benachrichtigungen',
    analytics: 'Datenanalyse',
    operationLogs: 'Aktionsprotokolle',
    roles: 'Rollenverwaltung',
    im: 'Kundenservice',
    supportChannels: 'Support-Kanäle',
    ads: 'Werbung',
    flashSale: 'Blitzverkauf',
    loginLogs: 'Login-Protokolle',
    luckyDraw: 'Glücksziehung',
    settings: 'Systemkonfiguration',
    pendingApplications: 'Ausstehende Anträge',

    // Blog Translation Progress Page
    blog_translation_pageTitle: 'Übersetzungsfortschritt-Übersicht',
    blog_translation_pageSubtitle:
      'Echtzeitüberwachung des Fortschritts und Status der Blog-Übersetzungen',
    blog_translation_autoRefreshOn: 'Automatische Aktualisierung',
    blog_translation_autoRefreshOff: 'Automatische Aktualisierung aktivieren',
    blog_translation_manualRefresh: 'Manuelle Aktualisierung',
    blog_translation_overallProgress: 'Gesamtfortschritt',
    blog_translation_completed: 'Abgeschlossen',
    blog_translation_inProgress: 'In Bearbeitung',
    blog_translation_failed: 'Fehlgeschlagen',
    blog_translation_completedItems:
      '{completed} / {total} Einträge abgeschlossen',
    blog_translation_articleTranslation: 'Artikelübersetzung',
    blog_translation_categoryTranslation: 'Kategorienübersetzung',
    blog_translation_tagTranslation: 'Tag-Übersetzung',
    blog_translation_queueStatus: 'Warteschlangenstatus',
    blog_translation_timeInfo: 'Zeitinformationen',
    blog_translation_startTime: 'Startzeit',
    blog_translation_notStarted: 'Nicht gestartet',
    blog_translation_elapsedTime: 'Verstrichene Zeit',
    blog_translation_estimatedCompletion: 'Geschätzter Abschluss',
    blog_translation_unknown: 'Unbekannt',
    blog_translation_pendingArticlesTitle: '🔍 Ausstehende Artikel ({lang})',
    blog_translation_pendingArticlesDescription:
      '{count} Artikel warten auf die Übersetzung in {lang}',
    blog_translation_allArticlesTranslated: 'Alle Artikel übersetzt',
    blog_translation_allArticlesTranslatedDesc:
      'Alle Artikel für die Sprache ({lang}) haben Übersetzungen',
    blog_translation_statusCompleted: 'Abgeschlossen',
    blog_translation_statusProcessing: 'Verarbeitung {progress}%',
    blog_translation_statusQueued: 'In der Warteschlange',
    blog_translation_statusFailed: 'Fehlgeschlagen',
    blog_translation_statusUntranslated: 'Unübersetzt',
    blog_translation_translateButton: 'Übersetzen',
    blog_translation_activeJobsTitle: '⚡ Aktive Übersetzungsjobs ({count})',
    blog_translation_noActiveJobs: 'Keine aktiven Übersetzungsjobs',
    blog_translation_typeArticle: 'Artikel',
    blog_translation_typeCategory: 'Kategorie',
    blog_translation_typeTag: 'Tag',
    blog_translation_issuesDetectionTitle: '🔍 Übersetzungsfehler-Erkennung',
    blog_translation_targetLanguage: 'Zielsprache',
    blog_translation_recheck: 'Erneut prüfen',
    blog_translation_selectAll: 'Alle auswählen',
    blog_translation_deselectAll: 'Auswahl aufheben',
    blog_translation_fixAll: 'Alle beheben',
    blog_translation_fixSelected: 'Ausgewählte beheben ({count})',
    blog_translation_issuesFound:
      '{count} Artikel mit Übersetzungsproblemen gefunden',
    blog_translation_articleTitle: 'Artikeltitel',
    blog_translation_issueType: 'Fehlertyp',
    blog_translation_severity: 'Schwere',
    blog_translation_issueTitleNotTranslated: 'Titel nicht übersetzt',
    blog_translation_issueContentIncomplete: 'Inhalt unvollständig',
    blog_translation_issueNotTranslated: 'Nicht übersetzt',
    blog_translation_issueFailed: 'Übersetzung fehlgeschlagen',
    blog_translation_severityHigh: 'Hoch',
    blog_translation_severityMedium: 'Mittel',
    blog_translation_severityLow: 'Niedrig',
    blog_translation_fixSingle: 'Beheben',
    blog_translation_noIssuesFound: 'Keine Übersetzungsprobleme gefunden',
    blog_translation_noIssuesFoundDesc:
      'Alle Artikel für die Sprache ({lang}) sind ordnungsgemäß übersetzt',
    blog_translation_jobHistoryTitle: '📋 Übersetzungshistorie',
    blog_translation_filter: 'Filter',
    blog_translation_showOnlyActive:
      'Nur aktive Jobs anzeigen (QUEUED/PROCESSING)',
    blog_translation_perPage: 'Pro Seite',
    blog_translation_perPageItems: '{count} Einträge',
    blog_translation_prevPage: 'Vorherige',
    blog_translation_currentPage: 'Seite {page}',
    blog_translation_nextPage: 'Nächste',
    blog_translation_name: 'Name',
    blog_translation_type: 'Typ',
    blog_translation_targetLang: 'Ziel',
    blog_translation_status: 'Status',
    blog_translation_progress: 'Fortschritt',
    blog_translation_createdAt: 'Erstellt am',
    blog_translation_errorMsg: 'Fehler',
    blog_translation_totalRecords:
      '{total} Datensätze insgesamt, Seite {page} / {totalPages}',
    blog_translation_noJobRecords: 'Keine Job-Einträge',
    blog_translation_liveJobsTitle: 'Live-Job-Queue',
    blog_translation_activeJobs: 'Aktive Jobs ({count})',
    blog_translation_waitingJobs: 'Wartende Jobs ({count})',
    blog_translation_failedJobs: 'Fehlgeschlagene Jobs ({count})',
    blog_translation_moreWaitingJobs: '{count} weitere Jobs warten',
    blog_translation_retry: 'Erneut versuchen',
    blog_translation_moreFailedJobs: '{count} weitere fehlgeschlagene Jobs',
    blog_translation_noLiveJobs: 'Keine aktiven Jobs in der Warteschlange',
    blog_translation_failedJobsAlertTitle: 'Fehlgeschlagene Jobs erkannt',
    blog_translation_failedJobsAlertDesc:
      '{count} Übersetzungsjobs sind fehlgeschlagen, prüfen Sie die fehlgeschlagenen Jobs.',
    blog_translation_notStartedAlertTitle: 'Übersetzung nicht gestartet',
    blog_translation_notStartedAlertDesc:
      'Alle Übersetzungsjobs warten, prüfen Sie den Queue-Status.',
    blog_translation_completedAlertTitle: 'Übersetzung abgeschlossen',
    blog_translation_completedAlertDesc:
      'Alle Übersetzungsjobs wurden erfolgreich abgeschlossen!',
    blog_translation_loadFailedTitle: 'Laden fehlgeschlagen',
    blog_translation_loadFailedDesc:
      'Fehler beim Laden der Übersetzungsfortschrittsdaten',
    blog_translation_retryButton: 'Erneut versuchen',
    blog_translation_batchFixStarted:
      'Batch-Korrektur gestartet, {count} Jobs in die Warteschlange gestellt',
    blog_translation_batchFixFailed:
      'Batch-Korrektur fehlgeschlagen, bitte später erneut versuchen',
    blog_translation_batchFixNetworkError:
      'Batch-Korrektur fehlgeschlagen, prüfen Sie die Netzwerkverbindung',
    blog_translation_seconds: '0s',
    blog_translation_progressWithPercent: 'Fortschritt: {progress}%',
    blog_translation_waiting: 'Wartet...',
    blog_translation_unknownError: 'Unbekannter Fehler',
    blog_article_translationRequestSent:
      'Übersetzungsanforderung gesendet, wird automatisch aktualisiert',
    blog_article_translationFailed:
      'Übersetzung fehlgeschlagen, bitte später erneut versuchen',
    blog_article_retranslate: 'Erneut übersetzen',
    blog_article_autoTranslateAfterSave:
      'Englische Version nach dem Speichern automatisch übersetzen',
  },
};

// 博客翻译进度卡片相关翻译
export const BLOG_TRANSLATION_CARD_TRANSLATIONS: Record<
  Locale,
  Record<string, string>
> = {
  en: {
    translationProgress: 'Translation Progress',
    loadFailed: 'Load failed',
    retry: 'Retry',
    viewDetails: 'View Details',
    inProgress: 'In Progress',
    failed: 'Failed',
    completed: 'Completed',
    articles: 'Articles',
    categories: 'Categories',
    tags: 'Tags',
    activeJobs: 'Active: {count}',
    waitingJobs: 'Waiting: {count}',
    completedJobs: 'Completed: {count}',
    failedJobsWarning: '⚠️ {count} jobs failed, please check',
    allJobsCompleted: 'All translation jobs completed',
    translationNotStarted: '⏳ Translation not started yet',
  },
  zh: {
    translationProgress: '翻译进度',
    loadFailed: '加载失败',
    retry: '重试',
    viewDetails: '查看详情',
    inProgress: '进行中',
    failed: '失败',
    completed: '已完成',
    articles: '文章',
    categories: '分类',
    tags: '标签',
    activeJobs: '进行中: {count}',
    waitingJobs: '等待中: {count}',
    completedJobs: '已完成: {count}',
    failedJobsWarning: '⚠️ 有 {count} 个任务失败，请检查',
    allJobsCompleted: '所有翻译任务已完成',
    translationNotStarted: '⏳ 翻译尚未开始',
  },
  ja: {},
  ko: {},
  fr: {},
  de: {},
};

export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  EDITOR: 'Editor',
  VIEWER: 'Viewer',
  FINANCE: 'Finance',
};
