import type { Locale } from '@lucky/shared';

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    users: 'User Management',
    admin: 'Admin Accounts',
    products: 'Products',
    categories: 'Categories',
    actSection: 'Act Sections',
    banners: 'Banners',
    groups: 'Group Buying',
    orders: 'Orders & Delivery',
    kyc: 'KYC Review',
    address: 'Address',
    marketing: 'Marketing',
    finance: 'Finance Center',
    finance_page: 'Finance',
    paymentChannels: 'Payment Channels',
    logout: 'Logout',
    revenue: 'Total Revenue',
    activeUsers: 'Active Users',
    newOrders: 'New Orders',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    status: 'Status',
    actions: 'Actions',
    kyc_pending: 'KYC Pending',
    notifications: 'Notifications',
    analytics: 'Data Analytics',
    operationLogs: 'Operation Logs',
    roles: 'Role Management',
    im: 'Customer Service',
    supportChannels: 'Support Channels',
    ads: 'Advertisements',
    flashSale: 'Flash Sale',
    loginLogs: 'Login Logs',
    luckyDraw: 'Lucky Draw',
    settings: 'System Config',
    pendingApplications: 'Pending Applications',
    
    // Blog Translation Progress Page
    blog_translation_pageTitle: 'Translation Progress Monitor',
    blog_translation_pageSubtitle: 'Real-time monitoring of blog content translation progress and status',
    blog_translation_autoRefreshOn: 'Auto refreshing',
    blog_translation_autoRefreshOff: 'Enable auto refresh',
    blog_translation_manualRefresh: 'Manual refresh',
    blog_translation_overallProgress: 'Overall Progress',
    blog_translation_completed: 'Completed',
    blog_translation_inProgress: 'In Progress',
    blog_translation_failed: 'Failed',
    blog_translation_completedItems: '{completed} / {total} items completed',
    blog_translation_articleTranslation: 'Article Translation',
    blog_translation_categoryTranslation: 'Category Translation',
    blog_translation_tagTranslation: 'Tag Translation',
    blog_translation_queueStatus: 'Queue Status',
    blog_translation_timeInfo: 'Time Information',
    blog_translation_startTime: 'Start Time',
    blog_translation_notStarted: 'Not started',
    blog_translation_elapsedTime: 'Elapsed',
    blog_translation_estimatedCompletion: 'Estimated completion',
    blog_translation_unknown: 'Unknown',
    blog_translation_pendingArticlesTitle: '🔍 Pending Articles ({lang})',
    blog_translation_pendingArticlesDescription: '{count} articles pending {lang} translation',
    blog_translation_allArticlesTranslated: 'All articles translated',
    blog_translation_allArticlesTranslatedDesc: 'All articles for language ({lang}) have translations',
    blog_translation_statusCompleted: 'Completed',
    blog_translation_statusProcessing: 'Processing {progress}%',
    blog_translation_statusQueued: 'Queued',
    blog_translation_statusFailed: 'Failed',
    blog_translation_statusUntranslated: 'Untranslated',
    blog_translation_translateButton: 'Translate',
    blog_translation_activeJobsTitle: '⚡ Active Translation Jobs ({count})',
    blog_translation_noActiveJobs: 'No active translation jobs',
    blog_translation_typeArticle: 'Article',
    blog_translation_typeCategory: 'Category',
    blog_translation_typeTag: 'Tag',
    blog_translation_issuesDetectionTitle: '🔍 Translation Issues Detection',
    blog_translation_targetLanguage: 'Target Language',
    blog_translation_recheck: 'Recheck',
    blog_translation_selectAll: 'Select All',
    blog_translation_deselectAll: 'Deselect All',
    blog_translation_fixAll: 'Fix All Issues',
    blog_translation_fixSelected: 'Fix Selected ({count})',
    blog_translation_issuesFound: '{count} articles with translation issues found',
    blog_translation_articleTitle: 'Article Title',
    blog_translation_issueType: 'Issue Type',
    blog_translation_severity: 'Severity',
    blog_translation_issueTitleNotTranslated: 'Title not translated',
    blog_translation_issueContentIncomplete: 'Content incomplete',
    blog_translation_issueNotTranslated: 'Not translated',
    blog_translation_issueFailed: 'Translation failed',
    blog_translation_severityHigh: 'High',
    blog_translation_severityMedium: 'Medium',
    blog_translation_severityLow: 'Low',
    blog_translation_fixSingle: 'Fix',
    blog_translation_noIssuesFound: 'No translation issues found',
    blog_translation_noIssuesFoundDesc: 'All articles for language ({lang}) are properly translated',
    blog_translation_jobHistoryTitle: '📋 Translation Job History',
    blog_translation_filter: 'Filter',
    blog_translation_showOnlyActive: 'Show only active jobs (QUEUED/PROCESSING)',
    blog_translation_perPage: 'Per page',
    blog_translation_perPageItems: '{count} items',
    blog_translation_prevPage: 'Previous',
    blog_translation_currentPage: 'Page {page}',
    blog_translation_nextPage: 'Next',
    blog_translation_name: 'Name',
    blog_translation_type: 'Type',
    blog_translation_targetLang: 'Target',
    blog_translation_status: 'Status',
    blog_translation_progress: 'Progress',
    blog_translation_createdAt: 'Created At',
    blog_translation_errorMsg: 'Error',
    blog_translation_totalRecords: '{total} records total, page {page} / {totalPages}',
    blog_translation_noJobRecords: 'No job records',
    blog_translation_liveJobsTitle: 'Live Job Queue',
    blog_translation_activeJobs: 'Active Jobs ({count})',
    blog_translation_waitingJobs: 'Waiting Jobs ({count})',
    blog_translation_failedJobs: 'Failed Jobs ({count})',
    blog_translation_moreWaitingJobs: '{count} more jobs waiting',
    blog_translation_retry: 'Retry',
    blog_translation_moreFailedJobs: '{count} more failed jobs',
    blog_translation_noLiveJobs: 'No active jobs in queue',
    blog_translation_failedJobsAlertTitle: 'Failed jobs detected',
    blog_translation_failedJobsAlertDesc: '{count} translation jobs failed, check failed jobs list.',
    blog_translation_notStartedAlertTitle: 'Translation not started',
    blog_translation_notStartedAlertDesc: 'All translation jobs are waiting, check queue status.',
    blog_translation_completedAlertTitle: 'Translation completed',
    blog_translation_completedAlertDesc: 'All translation jobs finished successfully!',
    blog_translation_loadFailedTitle: 'Load failed',
    blog_translation_loadFailedDesc: 'Failed to load translation progress data',
    blog_translation_retryButton: 'Retry',
    blog_translation_batchFixStarted: 'Batch fix started, {count} jobs queued',
    blog_translation_batchFixFailed: 'Batch fix failed, please try again later',
    blog_translation_batchFixNetworkError: 'Batch fix failed, check network connection',
    blog_translation_seconds: '0s',
    blog_translation_progressWithPercent: 'Progress: {progress}%',
    blog_translation_waiting: 'Waiting...',
    blog_translation_unknownError: 'Unknown error',
    blog_article_translationRequestSent: 'Translation request sent, will refresh automatically',
    blog_article_translationFailed: 'Translation failed, please try again later',
    blog_article_retranslate: 'Retranslate',
    blog_article_autoTranslateAfterSave: 'Auto-translate English version after saving',
    
    // Blog Dashboard Page
    blog_dashboard_pageTitle: 'Blog Management',
    blog_dashboard_pageDescription: 'Manage blog articles, categories, tags, and comments',
    blog_dashboard_writeNewArticle: 'Write New Article',
    blog_dashboard_totalArticles: 'Total Articles',
    blog_dashboard_categories: 'Categories',
    blog_dashboard_tags: 'Tags',
    blog_dashboard_pendingComments: 'Pending Comments',
    blog_dashboard_recentArticles: 'Recent Articles',
    blog_dashboard_viewAll: 'View All',
    blog_dashboard_article: 'Article',
    blog_dashboard_status: 'Status',
    blog_dashboard_views: 'Views',
    blog_dashboard_comments: 'Comments',
    blog_dashboard_published: 'Published',
    blog_dashboard_notPublished: 'Not published',
    blog_dashboard_topPerformingArticles: 'Top Performing Articles',
    blog_dashboard_recentActivity: 'Recent Activity',
    blog_dashboard_blogSystemReady: 'Blog system is ready',
    blog_dashboard_backendApiReady: 'Backend API fully implemented, ready to create content',
    blog_dashboard_welcomeToBlogSystem: 'Welcome to the blog system',
    blog_dashboard_startCreatingFirstArticle: 'Start creating your first blog article',
    blog_dashboard_analyticsDashboardAdded: 'Analytics dashboard added',
    blog_dashboard_trackArticlePerformance: 'Track article performance and user engagement',
    blog_dashboard_justNow: 'Just now',
    blog_dashboard_hoursAgo: '2 hours ago',
    blog_dashboard_loadingBlogDashboard: 'Loading blog dashboard...',
    blog_dashboard_numberOfPublishedArticles: 'Number of published articles',
    blog_dashboard_numberOfArticleCategories: 'Number of article categories',
    blog_dashboard_numberOfArticleTags: 'Number of article tags',
    blog_dashboard_commentsAwaitingModeration: 'Comments awaiting moderation',
    
    // Blog Articles Page
    blog_articles_pageTitle: 'Article Management',
    blog_articles_pageDescription: 'Manage blog articles including creation, editing, publishing, and deletion',
    blog_articles_newArticle: 'New Article',
    blog_articles_articleList: 'Article List',
    blog_articles_search: 'Search',
    blog_articles_searchPlaceholder: 'Search article titles or content...',
    blog_articles_status: 'Status',
    blog_articles_allStatus: 'All Status',
    blog_articles_published: 'Published',
    blog_articles_draft: 'Draft',
    blog_articles_archived: 'Archived',
    blog_articles_category: 'Category',
    blog_articles_allCategories: 'All Categories',
    blog_articles_article: 'Article',
    blog_articles_tags: 'Tags',
    blog_articles_metrics: 'Metrics',
    blog_articles_views: 'views',
    blog_articles_comments: 'comments',
    blog_articles_publishedDate: 'Published',
    blog_articles_notPublished: 'Not published',
    blog_articles_actions: 'Actions',
    blog_articles_preview: 'Preview',
    blog_articles_edit: 'Edit',
    blog_articles_unpublish: 'Unpublish',
    blog_articles_publish: 'Publish',
    blog_articles_delete: 'Delete',
    blog_articles_deleteArticle: 'Delete Article?',
    blog_articles_deleteConfirm: 'Delete',
    blog_articles_cancel: 'Cancel',
    blog_articles_articleDeleted: 'Article deleted successfully',
    blog_articles_deleteFailed: 'Failed to delete article',
    blog_articles_publishArticle: 'Publish Article?',
    blog_articles_publishConfirm: 'Publish',
    blog_articles_articlePublished: 'Article published successfully',
    blog_articles_publishFailed: 'Failed to publish article',
    blog_articles_unpublishArticle: 'Unpublish Article?',
    blog_articles_unpublishConfirm: 'Unpublish',
    blog_articles_articleUnpublished: 'Article unpublished successfully',
    blog_articles_unpublishFailed: 'Failed to unpublish article',
    blog_articles_actionCannotBeUndone: '⚠️ This action cannot be undone.',
    blog_articles_articleWillBePublic: '📢 Article will be publicly visible',
    blog_articles_articleWillBeHidden: '⚠️ Article will be hidden from public',
    blog_articles_articleDetails: 'Article Details:',
    blog_articles_slug: 'Slug:',
    blog_articles_author: 'Author:',
    blog_articles_uncategorized: 'Uncategorized',
    blog_articles_admin: 'Admin',
    blog_articles_min: 'min',
    
    // Blog Categories Page
    blog_categories_pageTitle: 'Category Management',
    blog_categories_pageDescription: 'Manage blog categories for organizing articles',
    blog_categories_newCategory: 'New Category',
    blog_categories_categoryList: 'Category List',
    blog_categories_search: 'Search',
    blog_categories_searchPlaceholder: 'Search by name or description...',
    blog_categories_name: 'Name',
    blog_categories_slug: 'Slug',
    blog_categories_description: 'Description',
    blog_categories_articles: 'Articles',
    blog_categories_created: 'Created',
    blog_categories_actions: 'Actions',
    blog_categories_deleteCategory: 'Delete Category?',
    blog_categories_deleteConfirm: 'Delete',
    blog_categories_cancel: 'Cancel',
    blog_categories_categoryDeleted: 'Category deleted successfully',
    blog_categories_deleteFailed: 'Failed to delete category',
    blog_categories_actionCannotBeUndone: '⚠️ This action cannot be undone.',
    blog_categories_categoryDetails: 'Category Details:',
    blog_categories_noDescription: 'No description',
    blog_categories_uncategorized: 'Uncategorized',
    blog_categories_categoryUsageTips: 'Category Usage Tips',
    blog_categories_tip1: 'Categories help organize articles into logical groups',
    blog_categories_tip2: 'Each article can belong to only one category',
    blog_categories_tip3: 'URL slugs should be lowercase with hyphens (e.g., "web-development")',
    blog_categories_tip4: 'Categories with articles cannot be deleted - move articles first',
    blog_categories_thisCategoryContains: 'This category contains {count} articles.',
    blog_categories_articlesWillBeMoved: 'These articles will be moved to "Uncategorized".',
    
    // Blog Tags Page
    blog_tags_pageTitle: 'Tag Management',
    blog_tags_pageDescription: 'Manage blog tags for categorizing and organizing articles',
    blog_tags_newTag: 'New Tag',
    blog_tags_tagList: 'Tag List',
    blog_tags_search: 'Search',
    blog_tags_searchPlaceholder: 'Search tags by name or description...',
    blog_tags_totalTags: 'Total Tags',
    blog_tags_taggedArticles: 'Tagged Articles',
    blog_tags_totalTagsCount: 'Total {count} tags',
    blog_tags_name: 'Name',
    blog_tags_slug: 'Slug',
    blog_tags_description: 'Description',
    blog_tags_articles: 'articles',
    blog_tags_uses: 'uses',
    blog_tags_created: 'Created',
    blog_tags_actions: 'Actions',
    blog_tags_deleteTag: 'Delete Tag?',
    blog_tags_deleteConfirm: 'Delete',
    blog_tags_cancel: 'Cancel',
    blog_tags_tagDeleted: 'Tag deleted successfully',
    blog_tags_deleteFailed: 'Failed to delete tag',
    blog_tags_loadFailed: 'Failed to load tags',
    blog_tags_actionCannotBeUndone: 'This action cannot be undone.',
    blog_tags_loadingTags: 'Loading tags...',
    blog_tags_noDescription: 'No description',
    blog_tags_tagUsageTips: 'Tag Usage Tips',
    blog_tags_tip1: 'Tags help categorize articles with multiple topics',
    blog_tags_tip2: 'Each article can have multiple tags (unlike categories)',
    blog_tags_tip3: 'Use specific, descriptive tags rather than generic ones',
    blog_tags_tip4: 'Popular tags are automatically highlighted in the blog',
    blog_tags_tip5: 'Tags can be merged if you have similar ones',
    blog_tags_showingTags: 'Showing 1 to {current} of {total} tags',
    
    // Blog Comments Page
    blog_comments_pageTitle: 'Comment Management',
    blog_comments_pageDescription: 'Moderate and manage user comments on blog articles',
    blog_comments_loadingComments: 'Loading comments...',
    blog_comments_totalComments: 'Total Comments',
    blog_comments_approved: 'Approved',
    blog_comments_pending: 'Pending',
    blog_comments_spam: 'Spam',
    blog_comments_searchPlaceholder: 'Search comments by content or author...',
    blog_comments_allStatus: 'All Status',
    blog_comments_allArticles: 'All Articles',
    blog_comments_commentList: 'Comment List',
    blog_comments_totalCommentsCount: 'Total {count} comments',
    blog_comments_pendingModeration: '{count} pending moderation',
    blog_comments_author: 'Author',
    blog_comments_email: 'Email',
    blog_comments_content: 'Content',
    blog_comments_article: 'Article',
    blog_comments_createdAt: 'Created',
    blog_comments_ipAddress: 'IP Address',
    blog_comments_actions: 'Actions',
    blog_comments_approve: 'Approve',
    blog_comments_reject: 'Reject',
    blog_comments_edit: 'Edit',
    blog_comments_delete: 'Delete',
    blog_comments_viewArticle: 'View Article',
    blog_comments_reply: 'Reply',
    blog_comments_commentApproved: 'Comment approved successfully',
    blog_comments_approveFailed: 'Failed to approve comment',
    blog_comments_commentRejected: 'Comment rejected successfully',
    blog_comments_rejectFailed: 'Failed to reject comment',
    blog_comments_commentDeleted: 'Comment deleted successfully',
    blog_comments_deleteFailed: 'Failed to delete comment',
    blog_comments_loadFailed: 'Failed to load comments',
    blog_comments_deleteConfirm: 'Are you sure you want to delete this comment? This action cannot be undone.',
    blog_comments_moderationTips: 'Comment Moderation Tips',
    blog_comments_tip1: 'Review pending comments regularly to maintain engagement',
    blog_comments_tip2: 'Mark obvious spam comments to help improve automatic filtering',
    blog_comments_tip3: 'Consider replying to constructive comments to build community',
    blog_comments_tip4: 'Check IP addresses and user agents for suspicious patterns',
    blog_comments_tip5: 'Use the search feature to find comments by specific users',
    blog_comments_showingComments: 'Showing 1 to {current} of {total} comments',
    blog_comments_unknownArticle: 'Unknown Article',
    blog_comments_untitled: 'Untitled',
  },
  zh: {
    dashboard: '仪表盘',
    users: '用户管理',
    admin: '管理员账号',
    products: '商品管理',
    categories: '分类管理',
    actSection: '活动区块',
    banners: 'Banner广告',
    groups: '拼团管理',
    orders: '订单与发货',
    kyc: 'KYC审核',
    address: '地址管理',
    marketing: '营销中心',
    finance: '财务中心',
    finance_page: '财务',
    paymentChannels: '支付渠道',
    logout: '退出登录',
    revenue: '总收入',
    activeUsers: '活跃用户',
    newOrders: '新增订单',
    add: '新增',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    search: '搜索...',
    status: '状态',
    actions: '操作',
    kyc_pending: 'KYC待审核',
    notifications: '通知管理',
    analytics: '数据分析',
    operationLogs: '操作日志',
    roles: '角色管理',
    im: '客服中心',
    supportChannels: '客服渠道',
    ads: '广告管理',
    flashSale: '限时秒杀',
    loginLogs: '登录日志',
    luckyDraw: '幸运抽奖',
    settings: '系统配置',
    pendingApplications: '待审核申请',
    
    // Blog Translation Progress Page
    blog_translation_pageTitle: '翻译进度监控',
    blog_translation_pageSubtitle: '实时监控博客内容翻译进度和状态',
    blog_translation_autoRefreshOn: '自动刷新中',
    blog_translation_autoRefreshOff: '开启自动刷新',
    blog_translation_manualRefresh: '手动刷新',
    blog_translation_overallProgress: '总体进度',
    blog_translation_completed: '完成',
    blog_translation_inProgress: '进行中',
    blog_translation_failed: '失败',
    blog_translation_completedItems: '已完成 {completed} / {total} 个项目',
    blog_translation_articleTranslation: '文章翻译',
    blog_translation_categoryTranslation: '分类翻译',
    blog_translation_tagTranslation: '标签翻译',
    blog_translation_queueStatus: '队列状态',
    blog_translation_timeInfo: '时间信息',
    blog_translation_startTime: '开始时间',
    blog_translation_notStarted: '未开始',
    blog_translation_elapsedTime: '已运行',
    blog_translation_estimatedCompletion: '预计完成',
    blog_translation_unknown: '未知',
    blog_translation_pendingArticlesTitle: '🔍 待翻译文章 ({lang})',
    blog_translation_pendingArticlesDescription: '共 {count} 篇文章尚未完成 {lang} 语言翻译',
    blog_translation_allArticlesTranslated: '所有文章已完成翻译',
    blog_translation_allArticlesTranslatedDesc: '当前语言 ({lang}) 的所有文章都有翻译版本',
    blog_translation_statusCompleted: '已完成',
    blog_translation_statusProcessing: '处理中 {progress}%',
    blog_translation_statusQueued: '排队中',
    blog_translation_statusFailed: '失败',
    blog_translation_statusUntranslated: '未翻译',
    blog_translation_translateButton: '翻译',
    blog_translation_activeJobsTitle: '⚡ 活跃翻译任务 ({count} 个)',
    blog_translation_noActiveJobs: '当前没有活跃翻译任务',
    blog_translation_typeArticle: '文章',
    blog_translation_typeCategory: '分类',
    blog_translation_typeTag: '标签',
    blog_translation_issuesDetectionTitle: '🔍 问题文章检测',
    blog_translation_targetLanguage: '目标语言',
    blog_translation_recheck: '重新检测',
    blog_translation_selectAll: '全选',
    blog_translation_deselectAll: '取消全选',
    blog_translation_fixAll: '修复所有问题',
    blog_translation_fixSelected: '修复选中 ({count})',
    blog_translation_issuesFound: '发现 {count} 篇文章有翻译问题',
    blog_translation_articleTitle: '文章标题',
    blog_translation_issueType: '问题类型',
    blog_translation_severity: '严重程度',
    blog_translation_issueTitleNotTranslated: '标题未翻译',
    blog_translation_issueContentIncomplete: '内容不完整',
    blog_translation_issueNotTranslated: '未翻译',
    blog_translation_issueFailed: '翻译失败',
    blog_translation_severityHigh: '高',
    blog_translation_severityMedium: '中',
    blog_translation_severityLow: '低',
    blog_translation_fixSingle: '单独修复',
    blog_translation_noIssuesFound: '未发现翻译问题',
    blog_translation_noIssuesFoundDesc: '当前语言 ({lang}) 的所有文章翻译正常',
    blog_translation_jobHistoryTitle: '📋 翻译任务记录（持久化）',
    blog_translation_filter: '筛选',
    blog_translation_showOnlyActive: '仅显示活跃任务 (QUEUED/PROCESSING)',
    blog_translation_perPage: '每页',
    blog_translation_perPageItems: '{count}条',
    blog_translation_prevPage: '上一页',
    blog_translation_currentPage: '第 {page} 页',
    blog_translation_nextPage: '下一页',
    blog_translation_name: '名称',
    blog_translation_type: '类型',
    blog_translation_targetLang: '目标语言',
    blog_translation_status: '状态',
    blog_translation_progress: '进度',
    blog_translation_createdAt: '创建时间',
    blog_translation_errorMsg: '错误信息',
    blog_translation_totalRecords: '共 {total} 条记录，第 {page} / {totalPages} 页',
    blog_translation_noJobRecords: '暂无翻译任务记录',
    blog_translation_liveJobsTitle: '实时任务列表',
    blog_translation_activeJobs: '进行中的任务 ({count})',
    blog_translation_waitingJobs: '等待中的任务 ({count})',
    blog_translation_failedJobs: '失败的任务 ({count})',
    blog_translation_moreWaitingJobs: '还有 {count} 个任务在等待中',
    blog_translation_retry: '重试',
    blog_translation_moreFailedJobs: '还有 {count} 个失败任务',
    blog_translation_noLiveJobs: '当前没有活跃的翻译任务',
    blog_translation_failedJobsAlertTitle: '存在失败任务',
    blog_translation_failedJobsAlertDesc: '有 {count} 个翻译任务失败，请检查失败任务列表。',
    blog_translation_notStartedAlertTitle: '翻译未开始',
    blog_translation_notStartedAlertDesc: '所有翻译任务都在等待中，请检查队列状态。',
    blog_translation_completedAlertTitle: '翻译完成',
    blog_translation_completedAlertDesc: '所有翻译任务已完成！',
    blog_translation_loadFailedTitle: '加载失败',
    blog_translation_loadFailedDesc: '无法获取翻译进度数据',
    blog_translation_retryButton: '重试',
    blog_translation_batchFixStarted: '批量修复已启动，已投递 {count} 个修复任务到队列',
    blog_translation_batchFixFailed: '批量修复失败，请稍后重试',
    blog_translation_batchFixNetworkError: '批量修复失败，请检查网络连接',
    blog_translation_seconds: '0秒',
    blog_translation_progressWithPercent: '进度: {progress}%',
    blog_translation_waiting: '等待中...',
    blog_translation_unknownError: '未知错误',
    blog_article_translationRequestSent: '翻译请求已发送，稍后将自动刷新',
    blog_article_translationFailed: '翻译失败，请稍后重试',
    blog_article_retranslate: '重新翻译',
    blog_article_autoTranslateAfterSave: '保存后自动翻译英文版本',
    
    // Blog Dashboard Page
    blog_dashboard_pageTitle: '博客管理',
    blog_dashboard_pageDescription: '管理博客文章、分类、标签和评论',
    blog_dashboard_writeNewArticle: '写新文章',
    blog_dashboard_totalArticles: '文章总数',
    blog_dashboard_categories: '分类',
    blog_dashboard_tags: '标签',
    blog_dashboard_pendingComments: '待审核评论',
    blog_dashboard_recentArticles: '最近文章',
    blog_dashboard_viewAll: '查看全部',
    blog_dashboard_article: '文章',
    blog_dashboard_status: '状态',
    blog_dashboard_views: '浏览量',
    blog_dashboard_comments: '评论',
    blog_dashboard_published: '发布时间',
    blog_dashboard_notPublished: '未发布',
    blog_dashboard_topPerformingArticles: '热门文章',
    blog_dashboard_recentActivity: '最近动态',
    blog_dashboard_blogSystemReady: '博客系统已就绪',
    blog_dashboard_backendApiReady: '后端API已完全实现，可以开始创建内容',
    blog_dashboard_welcomeToBlogSystem: '欢迎使用博客系统',
    blog_dashboard_startCreatingFirstArticle: '开始创建您的第一篇博客文章',
    blog_dashboard_analyticsDashboardAdded: '分析仪表板已添加',
    blog_dashboard_trackArticlePerformance: '跟踪文章表现和用户参与度',
    blog_dashboard_justNow: '刚刚',
    blog_dashboard_hoursAgo: '2小时前',
    blog_dashboard_loadingBlogDashboard: '正在加载博客仪表板...',
    blog_dashboard_numberOfPublishedArticles: '已发布文章数量',
    blog_dashboard_numberOfArticleCategories: '文章分类数量',
    blog_dashboard_numberOfArticleTags: '文章标签数量',
    blog_dashboard_commentsAwaitingModeration: '等待审核的评论',
    
    // Blog Articles Page
    blog_articles_pageTitle: '文章管理',
    blog_articles_pageDescription: '管理博客文章，包括创建、编辑、发布和删除',
    blog_articles_newArticle: '新建文章',
    blog_articles_articleList: '文章列表',
    blog_articles_search: '搜索',
    blog_articles_searchPlaceholder: '搜索文章标题或内容...',
    blog_articles_status: '状态',
    blog_articles_allStatus: '所有状态',
    blog_articles_published: '已发布',
    blog_articles_draft: '草稿',
    blog_articles_archived: '已归档',
    blog_articles_category: '分类',
    blog_articles_allCategories: '所有分类',
    blog_articles_article: '文章',
    blog_articles_tags: '标签',
    blog_articles_metrics: '数据',
    blog_articles_views: '浏览量',
    blog_articles_comments: '评论',
    blog_articles_publishedDate: '发布时间',
    blog_articles_notPublished: '未发布',
    blog_articles_actions: '操作',
    blog_articles_preview: '预览',
    blog_articles_edit: '编辑',
    blog_articles_unpublish: '取消发布',
    blog_articles_publish: '发布',
    blog_articles_delete: '删除',
    blog_articles_deleteArticle: '删除文章？',
    blog_articles_deleteConfirm: '删除',
    blog_articles_cancel: '取消',
    blog_articles_articleDeleted: '文章删除成功',
    blog_articles_deleteFailed: '删除文章失败',
    blog_articles_publishArticle: '发布文章？',
    blog_articles_publishConfirm: '发布',
    blog_articles_articlePublished: '文章发布成功',
    blog_articles_publishFailed: '发布文章失败',
    blog_articles_unpublishArticle: '取消发布文章？',
    blog_articles_unpublishConfirm: '取消发布',
    blog_articles_articleUnpublished: '文章取消发布成功',
    blog_articles_unpublishFailed: '取消发布文章失败',
    blog_articles_actionCannotBeUndone: '⚠️ 此操作无法撤销。',
    blog_articles_articleWillBePublic: '📢 文章将对公众可见',
    blog_articles_articleWillBeHidden: '⚠️ 文章将对公众隐藏',
    blog_articles_articleDetails: '文章详情：',
    blog_articles_slug: '链接：',
    blog_articles_author: '作者：',
    blog_articles_uncategorized: '未分类',
    blog_articles_admin: '管理员',
    blog_articles_min: '分钟',
    
    // Blog Categories Page
    blog_categories_pageTitle: '分类管理',
    blog_categories_pageDescription: '管理博客分类，用于组织文章',
    blog_categories_newCategory: '新建分类',
    blog_categories_categoryList: '分类列表',
    blog_categories_search: '搜索',
    blog_categories_searchPlaceholder: '按名称或描述搜索...',
    blog_categories_name: '名称',
    blog_categories_slug: '链接',
    blog_categories_description: '描述',
    blog_categories_articles: '文章数',
    blog_categories_created: '创建时间',
    blog_categories_actions: '操作',
    blog_categories_deleteCategory: '删除分类？',
    blog_categories_deleteConfirm: '删除',
    blog_categories_cancel: '取消',
    blog_categories_categoryDeleted: '分类删除成功',
    blog_categories_deleteFailed: '删除分类失败',
    blog_categories_actionCannotBeUndone: '⚠️ 此操作无法撤销。',
    blog_categories_categoryDetails: '分类详情：',
    blog_categories_noDescription: '无描述',
    blog_categories_uncategorized: '未分类',
    blog_categories_categoryUsageTips: '分类使用提示',
    blog_categories_tip1: '分类帮助将文章组织成逻辑组',
    blog_categories_tip2: '每篇文章只能属于一个分类',
    blog_categories_tip3: 'URL链接应为小写并用连字符连接（例如："web-development"）',
    blog_categories_tip4: '包含文章的分类无法删除 - 请先移动文章',
    blog_categories_thisCategoryContains: '此分类包含 {count} 篇文章。',
    blog_categories_articlesWillBeMoved: '这些文章将被移动到"未分类"。',
    
    // Blog Tags Page
    blog_tags_pageTitle: '标签管理',
    blog_tags_pageDescription: '管理博客标签，用于分类和组织文章',
    blog_tags_newTag: '新建标签',
    blog_tags_tagList: '标签列表',
    blog_tags_search: '搜索',
    blog_tags_searchPlaceholder: '按名称或描述搜索标签...',
    blog_tags_totalTags: '标签总数',
    blog_tags_taggedArticles: '已标记文章',
    blog_tags_totalTagsCount: '共 {count} 个标签',
    blog_tags_name: '名称',
    blog_tags_slug: '链接',
    blog_tags_description: '描述',
    blog_tags_articles: '篇文章',
    blog_tags_uses: '次使用',
    blog_tags_created: '创建时间',
    blog_tags_actions: '操作',
    blog_tags_deleteTag: '删除标签？',
    blog_tags_deleteConfirm: '删除',
    blog_tags_cancel: '取消',
    blog_tags_tagDeleted: '标签删除成功',
    blog_tags_deleteFailed: '删除标签失败',
    blog_tags_loadFailed: '加载标签失败',
    blog_tags_actionCannotBeUndone: '此操作无法撤销。',
    blog_tags_loadingTags: '正在加载标签...',
    blog_tags_noDescription: '无描述',
    blog_tags_tagUsageTips: '标签使用提示',
    blog_tags_tip1: '标签帮助将文章按多个主题分类',
    blog_tags_tip2: '每篇文章可以有多个标签（与分类不同）',
    blog_tags_tip3: '使用具体、描述性的标签，而不是通用标签',
    blog_tags_tip4: '热门标签会在博客中自动高亮显示',
    blog_tags_tip5: '如果有相似的标签，可以合并它们',
    blog_tags_showingTags: '显示第 1 到 {current} 个标签，共 {total} 个',
    
    // Blog Comments Page
    blog_comments_pageTitle: '评论管理',
    blog_comments_pageDescription: '审核和管理博客文章的用户评论',
    blog_comments_loadingComments: '正在加载评论...',
    blog_comments_totalComments: '评论总数',
    blog_comments_approved: '已批准',
    blog_comments_pending: '待审核',
    blog_comments_spam: '垃圾评论',
    blog_comments_searchPlaceholder: '按内容或作者搜索评论...',
    blog_comments_allStatus: '所有状态',
    blog_comments_allArticles: '所有文章',
    blog_comments_commentList: '评论列表',
    blog_comments_totalCommentsCount: '共 {count} 条评论',
    blog_comments_pendingModeration: '{count} 条待审核',
    blog_comments_author: '作者',
    blog_comments_email: '邮箱',
    blog_comments_content: '内容',
    blog_comments_article: '文章',
    blog_comments_createdAt: '创建时间',
    blog_comments_ipAddress: 'IP地址',
    blog_comments_actions: '操作',
    blog_comments_approve: '批准',
    blog_comments_reject: '拒绝',
    blog_comments_edit: '编辑',
    blog_comments_delete: '删除',
    blog_comments_viewArticle: '查看文章',
    blog_comments_reply: '回复',
    blog_comments_commentApproved: '评论批准成功',
    blog_comments_approveFailed: '批准评论失败',
    blog_comments_commentRejected: '评论拒绝成功',
    blog_comments_rejectFailed: '拒绝评论失败',
    blog_comments_commentDeleted: '评论删除成功',
    blog_comments_deleteFailed: '删除评论失败',
    blog_comments_loadFailed: '加载评论失败',
    blog_comments_deleteConfirm: '确定要删除此评论吗？此操作无法撤销。',
    blog_comments_moderationTips: '评论审核提示',
    blog_comments_tip1: '定期审核待处理评论以保持用户参与度',
    blog_comments_tip2: '标记明显的垃圾评论以帮助改进自动过滤',
    blog_comments_tip3: '考虑回复建设性评论以建立社区',
    blog_comments_tip4: '检查IP地址和用户代理以发现可疑模式',
    blog_comments_tip5: '使用搜索功能查找特定用户的评论',
    blog_comments_showingComments: '显示第 1 到 {current} 条评论，共 {total} 条',
    blog_comments_unknownArticle: '未知文章',
    blog_comments_untitled: '无标题',
  },
  ja: {},
  ko: {},
  fr: {},
  de: {},
};

// 博客翻译进度卡片相关翻译
export const BLOG_TRANSLATION_CARD_TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    translationProgress: 'Translation Progress',
    loadFailed: 'Load failed',
    retry: 'Retry',
    viewDetails: 'View Details',
    inProgress: 'In Progress',
    failed: 'Failed',
    completed: 'Completed',
    articles: 'Articles',
    categories: 'Categories',
    tags: 'Tags',
    activeJobs: 'Active: {count}',
    waitingJobs: 'Waiting: {count}',
    completedJobs: 'Completed: {count}',
    failedJobsWarning: '⚠️ {count} jobs failed, please check',
    allJobsCompleted: 'All translation jobs completed',
    translationNotStarted: '⏳ Translation not started yet',
  },
  zh: {
    translationProgress: '翻译进度',
    loadFailed: '加载失败',
    retry: '重试',
    viewDetails: '查看详情',
    inProgress: '进行中',
    failed: '失败',
    completed: '已完成',
    articles: '文章',
    categories: '分类',
    tags: '标签',
    activeJobs: '进行中: {count}',
    waitingJobs: '等待中: {count}',
    completedJobs: '已完成: {count}',
    failedJobsWarning: '⚠️ 有 {count} 个任务失败，请检查',
    allJobsCompleted: '所有翻译任务已完成',
    translationNotStarted: '⏳ 翻译尚未开始',
  },
  ja: {},
  ko: {},
  fr: {},
  de: {},
};

export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  EDITOR: 'Editor',
  VIEWER: 'Viewer',
  FINANCE: 'Finance',
};
